### ISSUE TITLE
Feature request: adjust color and Legend according to freely defined cutoff lines

### ISSUE THREAD

**Issue by benqhan** [kevinblighe/EnhancedVolcano#10]
Hi, Kevin. Thank you for your effort in EnhancedVolcano. It’s very useful in my work dealing with quantitative proteomics data. 
I see you have added the functions 'hline' and 'vline' to display extra cutoff lines besides to the original lines defined via ‘pCutoff’ and ‘FCcutoff’.  Is it possible to color each area segmented by cutoff lines, no matter it is ‘pCutoff’, ‘FCcutoff’, ‘hline’ or ‘vline’ that defined the cutoff?
For example, I used ‘pCutoff’ and ‘FCcutoff’ to set cutoff lines, I want to color the significantly up-regulated genes (p<0.05 & foldchange >logRatio) ‘red’, color the significantly down-regulated genes (p<0.05 & foldchange < -logRatio) ‘green’, and leave other points default (‘black’). Can not achieve this using current version of EnhancedVolcano.
For another specific circumstance, I want a plot that focus on the up-regulated proteins, with two different thresholds, e.g. 2>foldchange >=1, and foldchange >= 2. If I use a ‘hline’ to define ‘p<0.05’, use two ‘vline’ to define ‘2>foldchange >=1’ and ‘foldchange >= 2’, what can I do to color ‘’p<0.05 & foldchange >= 2” and “p<0.05 & 2>foldchange >=1” differently?
Moreover, the Legend corresponding to each area and its color defined by the above cutoff lines, may need to be adjusted.
P.S. If change the arguments like ‘transcriptPointSize’, ‘transcriptLabSize’ to ‘PointSize’, ‘LabSize’, I think it will be more concise and helpful, because it may be gene, protein, or other subjects besides to transcript.
Thank you very much!

**Comment by kevinblighe** [comment]
Hey, thank you for using the package. To avail of the most up to date version of the package, you should download the development version direct from GitHub. These changes will then eventually carry through to the main release on Bioconductor.

To do what you want, I believe you can use the _colCustom_ parameter. Please take a look at this example in the vignette: https://github.com/kevinblighe/EnhancedVolcano#over-ride-colouring-scheme-with-custom-key-value-pairs 

Can you take a look?

On the other part, yes, I had wondered what was the most appropriate name to use! Most volvanos are generated from gene expression data, so, one is usually thinking along those lines when writing the package. I can possibly add aliases for these parameters in the future version to ensure backward compatibility.

Thanks.

**Comment by benqhan** [comment]
It worked well! Thanks a lot.

**Comment by kevinblighe** [comment]
Cool - thank you for getting back to me. I will make a note regarding the parameter names (‘transcriptPointSize’, ‘transcriptLabSize', _et cetera_)

**Comment by kevinblighe** [comment]
Just re-opening this to remind me to address the parameter naming (‘_transcriptPointSize_’, ‘_transcriptLabSize_', _et cetera_) for the next Bioconductor release (Bioc 3.10). Bioc 3.9 was released just yesterday (May 3).

**Comment by kevinblighe** [comment]
The new parameters will be in v1.4 when it is released with Bioc 3.10. Basically, transcriptPointSize, transcriptLabSize, transcriptLabCol, transcriptLabFace, transcriptLabhjust, and transcriptLabvjust are now deprecated. One can use pointSize, labSize, labCol, labFace, labhjust, and labvjust, respectively, instead.

Thanks!

**Comment by ramarquezo** [comment]
I'm working with RStudio, I cannot work with any: pointSize, labSize, labCol, labFace, labhjust, and labvjust, the transcriptPointSize and transcriptLabSize work but transcriptLabCol, transcriptLabFace, transcriptLabhjust, and transcriptLabvjust do not work to me, so what can I do? I'm working in Rstudio in windows...... thanks a lot! By the way your program is amazing!

**Comment by kevinblighe** [comment]
Hey ramarquezo,

To use pointSize, labSize, labCol, etc, you will have to download the development version via:

```
devtools::install_github('kevinblighe/EnhancedVolcano')
```

These parameters are the exact same as the older versions, i.e., transcriptPointSize, transcriptLabSize, transcriptLabCol, etc.
