### ISSUE TITLE
background label

### ISSUE THREAD

**Issue by lmanchon** [kevinblighe/EnhancedVolcano#100]
-Hi,
is there an option to set background color of boxedLabels ?
thank you --

**Comment by kevinblighe** [comment]
Hi, there is not currently a way to do this. However, I have implemented it in my other package, PCAtools - please see lines:
https://github.com/kevinblighe/PCAtools/blob/master/R/biplot.R#L20-L23
https://github.com/kevinblighe/PCAtools/blob/master/R/biplot.R#L213
https://github.com/kevinblighe/PCAtools/blob/master/R/biplot.R#L437-L450

To add it to your volcanos, it should be as easy as:
`EnhancedVolcano(...) + geom_label_repel(fill = 'pink')
`

**Comment by lmanchon** [comment]
EnhancedVolcano(...) + geom_label_repel(fill = 'pink') 

failed, it doesn't work:

Error in `check_required_aesthetics()`:
! geom_label_repel requires the following missing aesthetics: label
Run `rlang::last_error()` to see where the error occurred.

**Comment by kevinblighe** [comment]
Please try to replicate the entire code chunk, adding it as geom_label_repel() in the way that I have shown.
https://github.com/kevinblighe/PCAtools/blob/master/R/biplot.R#L437-L450

**Comment by kevinblighe** [comment]
I have no funding for these packages, and, irrespective of that, neither have time, despite working literally every day for the past ~8 years.

You are welcome to implement the fix yourself via a Pull Request.
