### ISSUE TITLE
P cutoff 

### ISSUE THREAD

**Issue by carlosaya2** [kevinblighe/EnhancedVolcano#104]
Thank you for great tool.

this is rather a stupid question. 

I am applying a 0.05 pvalue cutoff which log10 is -1.3. the problem is that it is not showing that threshold on the plot. I think it is because the way is requested in the function 10e-6. does it need to match the 10e- format? 

![image](https://user-images.githubusercontent.com/61134130/178229971-9dc7bcf5-edf0-4637-81e6-e68ed9d3dcc3.png)

cheers

carlos

**Comment by kevinblighe** [comment]
Hi @carlosaya2 , for the `pCutoff `parameter, the value should be set as 0.05. Then, `EnhancedVolcano `will transform this to the -log10 scale internally.

Let me know if that resolves the problem.

Kind regards,
Kevin
