### ISSUE TITLE
Rownames despite below threshold

### ISSUE THREAD

**Issue by susheelbhanu** [kevinblighe/EnhancedVolcano#11]
[Hi, 
Thank you for this awesome package. I managed to generate a volcano plot, however, most of the genes of interest are not greater than 2-fold change. Is there anyway to still force the plot to give me their names on the plot itself. Here is my code and my plot:
```
EnhancedVolcano(topT,
                lab = rownames(topT),
                x = 'log2FoldChange',
                y = 'pvalue',
                xlim = c(-8, 8),
                title = 'VD versus CSD',
                pCutoff = 10e-3,
                FCcutoff = 1.5,
                transcriptPointSize = 2.5,
                transcriptLabSize = 3.0,
                legend=c('NS','Log2 fold-change','P value',
                         'P value & Log2 fold-change'),
                legendPosition = 'right',
                legendLabSize = 16,
                legendIconSize = 5.0,
                colAlpha = 1)
```
![kegg_volcano](https://user-images.githubusercontent.com/9979661/53491783-80fc4580-3a97-11e9-8814-1a8f1dbf7fd1.png)

**Comment by susheelbhanu** [comment]
Also, is there a way to get a list of all the significantly different genes as an output file (.CSV or .TXT)?

Thank you for your help!

**Comment by kevinblighe** [comment]
Hey Susheel - thanks! You could add the genes that you want to label to `selectLab`, and I believe that will label them even if they are below the threshold. Can you try that?

To output the results, I would just use the base R functions, for example, to output genes with P<0.05:
```
out <- subset(res, P < 0.05)
write.table(out, "out.tsv", sep='\t', row.names = FALSE, col.names = TRUE, quote = FALSE)
```

**Comment by susheelbhanu** [comment]
Hey Kevin, 

Thank you very much for the super-prompt reply. I tried the selectLab option with the following:
```
celltype1 <- c('Subdoligranulum variabile','Eubacterium rectale')
keyvals <- rep('black', nrow(topT))
p1 <- EnhancedVolcano(topT,
                      lab = rownames(topT),
                      x = 'log2FoldChange',
                      y = 'pvalue',
                      selectLab = celltype1,
                      xlim = c(-6.5,6.5),
                      xlab = bquote(~Log[2]~ 'fold change'),
                      title = 'Shading cell-type 1',
                      pCutoff = 10e-14,
                      FCcutoff = 1.0,
                      transcriptPointSize = 8.0,
                      transcriptLabSize = 5.0,
                      transcriptLabCol = 'purple',
                      transcriptLabFace = 'bold',
                      boxedlabels = TRUE,
                      shape = 42,
                      colCustom = keyvals,
                      colAlpha = 1,
                      legendPosition = 'top',
                      legendLabSize = 15,
                      legendIconSize = 5.0,
                      shade = celltype1,
                      shadeLabel = 'Cell-type I',
                      shadeAlpha = 1/2,
                      shadeFill = 'purple',
                      shadeSize = 1,
                      shadeBins = 5,
                      drawConnectors = TRUE,
                      widthConnectors = 1.0,
                      colConnectors = 'grey30',
                      gridlines.major = TRUE,
                      gridlines.minor = FALSE,
                      border = 'partial',
                      borderWidth = 1.5,
                      borderColour = 'black')
```
However, that didn't seem to work. Sorry. I am attaching the file, if it will help. 4 samples are control and the last 4 are the experimental

Thank you!
[EdgeR_filtered_V6.txt](https://github.com/kevinblighe/EnhancedVolcano/files/2910646/EdgeR_filtered_V6.txt)

**Comment by kevinblighe** [comment]
Okay, I will try to take a look later.

**Comment by kevinblighe** [comment]
Hey, I was hoping for the differential expression results table ... ? In any case, I just tested and the selectLab parameter will label genes that do not pass the thresholds. I notice, however, in your code that you have specified:

`selectLab = celltype1`

The value that is passed to selectLab is supposed to be a character vector, which comprises specific genes that you want to label. These will be genes that are contained within `rownames(topT)`.

Take a look at the example here: https://github.com/kevinblighe/EnhancedVolcano#only-label-key-transcripts

**Comment by susheelbhanu** [comment]
Thank you very much, Kevin! That worked. However, some of the rownames of topT, even though they are listed when I call rownames(topT) are not displayed on the plot. For example: "Parabacteroides distasonis". Any thoughts? Is it because they are cut-off due to the pcutoff and F-cutoff? Or are those just to draw the lines?

Thanks again for your help!.

**Comment by kevinblighe** [comment]
Yes, there may just not be any room for the labels. You could try to fit them in by adding `drawConnectors = TRUE` ?

**Comment by susheelbhanu** [comment]
```
EnhancedVolcano(topT,
                lab = rownames(topT),
                x = 'log2FoldChange',
                y = 'pvalue',
                xlim = c(-8, 8),
                title = 'VD versus CSD',
                pCutoff = 10e-3,
                FCcutoff = 1.5,
                transcriptPointSize = 2.5,
                transcriptLabSize = 3.0,
                legend=c('NS','Log2 fold-change','P value',
                         'P value & Log2 fold-change'),
                legendPosition = 'right',
                legendLabSize = 16,
                legendIconSize = 5.0,
                colAlpha = 1,
                drawConnectors = TRUE,
                widthConnectors = 0.2,
                colConnectors = 'grey30',
                selectLab = c("Parabacteroides distasonis"))
```
I did. No luck. Thank you for looking into this!

**Comment by kevinblighe** [comment]
"Parabacteroides distasonis" is definitely a part of `rownames(topT)`

**Comment by kevinblighe** [comment]
Any further updates?

**Comment by susheelbhanu** [comment]
No, Kevin. Some of the rownames don't seem to show up. I haven't been able to locate any patterns in the ones that are showing up in the plot. Based in the adj.p value and through log2 fold change, I've managed to locate the ones of interest in the plot and added them manually for the moment. I'll go back to the original dataset when I'm done with this abstract. Thanks again for your help!

**Comment by kevinblighe** [comment]
Okay, for now, I could not reproduce the issue with test data. The function behaves as expected from my end, i.e., it will label genes passed to selectLab even if they do not pass the thresholds for p-value and fold change.

**Comment by susheelbhanu** [comment]
Okay, thank you! You may close the issue if you like. I'll get in touch again if I run into something else. Thanks again for all the prompt help!

**Comment by kevinblighe** [comment]
Sure thing
