### ISSUE TITLE
Missing arrguments

### ISSUE THREAD

**Issue by seymoo** [kevinblighe/EnhancedVolcano#12]
Hi Kevin,

Thanks a lot for making this great package!
I am not so sure, but some of the arguments in the `EnhancedVolcano` function are missing for me: for example `shape, hline, boxedlabels`. 
Am I wrong or ?

**Comment by kevinblighe** [comment]
Hey. I think that I know what is the problem. The most update version of *EnhancedVolcano* is not yet officially released on Bioconductor - it will be released in Bioconductor 3.9, coming 'soon'.

For now, you can use these parameters (`shape`, `hline`, *et cetera*) by installing the development version with:

```
  devtools::install_github('kevinblighe/EnhancedVolcano')

```

Let me know if this works!

**Comment by seymoo** [comment]
> 
> 
> Hey. I think that I know what is the problem. The most update version of _EnhancedVolcano_ is not yet officially released on Bioconductor - it will be released in Bioconductor 3.9, coming 'soon'.
> 
> For now, you can use these parameters (`shape`, `hline`, _et cetera_) by installing the development version with:
> 
> ```
>   devtools::install_github('kevinblighe/EnhancedVolcano')
> ```
> 
> Let me know if this works!

I did that but it didn't work.

**Comment by kevinblighe** [comment]
Hey, perhaps you can show me the output when you try to install it, and also mention your version of R. You could also try to add `force = TRUE`, like I do here:

```
devtools::install_github('kevinblighe/EnhancedVolcano', force=TRUE)

Downloading GitHub repo kevinblighe/EnhancedVolcano@master
✔  checking for file ‘/tmp/RtmpdsvRUn/remotes1d7a497dee3f/kevinblighe-EnhancedVolcano-17ab9ef/DESCRIPTION’ (455ms)
─  preparing ‘EnhancedVolcano’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘EnhancedVolcano_1.1.3.tar.gz’
   
Installing package into ‘/home/kblighe/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘EnhancedVolcano’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (EnhancedVolcano)
```

Load it:
```
require(EnhancedVolcano)
Carregando pacotes exigidos: EnhancedVolcano
Carregando pacotes exigidos: ggplot2
Carregando pacotes exigidos: ggrepel
```

Check function parameters:
```
EnhancedVolcano
function (toptable, lab, x, y, selectLab = NULL, xlim = c(min(toptable[, 
    x], na.rm = TRUE), max(toptable[, x], na.rm = TRUE)), ylim = c(0, 
    max(-log10(toptable[, y]), na.rm = TRUE) + 5), xlab = bquote(~Log[2] ~ 
    "fold change"), ylab = bquote(~-Log[10] ~ italic(P)), axisLabSize = 18, 
    title = "Volcano plot", subtitle = "Bioconductor package EnhancedVolcano", 
    caption = paste0("Total = ", nrow(toptable), " variables"), 
    titleLabSize = 18, subtitleLabSize = 14, captionLabSize = 14, 
    pCutoff = 1e-05, pLabellingCutoff = pCutoff, FCcutoff = 1, 
    cutoffLineType = "longdash", cutoffLineCol = "black", cutoffLineWidth = 0.4, 
    transcriptPointSize = 0.8, transcriptLabSize = 3, transcriptLabCol = "black", 
    transcriptLabFace = "plain", transcriptLabhjust = 0, transcriptLabvjust = 1.5, 
    boxedlabels = FALSE, shape = 19, shapeCustom = NULL, col = c("grey30", 
        "forestgreen", "royalblue", "red2"), colCustom = NULL, 
    colAlpha = 1/2, legend = c("NS", "Log2 FC", "P", "P & Log2 FC"), 
    legendPosition = "top", legendLabSize = 14, legendIconSize = 4, 
    legendVisible = TRUE, shade = NULL, shadeLabel = NULL, shadeAlpha = 1/2, 
    shadeFill = "grey", shadeSize = 0.01, shadeBins = 2, drawConnectors = FALSE, 
    widthConnectors = 0.5, typeConnectors = "closed", endsConnectors = "first", 
    lengthConnectors = unit(0.01, "npc"), colConnectors = "grey10", 
    hline = NULL, hlineType = "longdash", hlineCol = "black", 
    hlineWidth = 0.4, vline = NULL, vlineType = "longdash", vlineCol = "black", 
    vlineWidth = 0.4, gridlines.major = TRUE, gridlines.minor = TRUE, 
    border = "partial", borderWidth = 0.8, borderColour = "black")
```

All of the ones that you list are there.

**Comment by seymoo** [comment]
`> devtools::install_github('kevinblighe/EnhancedVolcano')
Downloading GitHub repo kevinblighe/EnhancedVolcano@master
√  checking for file 'C:\Windows\Temp\RtmpspWctS\remotes271448d44ca0\kevinblighe-EnhancedVolcano-17ab9ef/DESCRIPTION' ...
-  preparing 'EnhancedVolcano':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'EnhancedVolcano_1.1.3.tar.gz'
   
Installing package into ‘E:/Myfiles/Rwork.space/R-3.3.2/library’
(as ‘lib’ is unspecified)
* installing *source* package 'EnhancedVolcano' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: package 'ggplot2' was built under R version 3.5.2
** help
*** installing help indices
  converting help for package 'EnhancedVolcano'
    finding HTML links ... done
    EnhancedVolcano-package                 html  
    EnhancedVolcano                         html  
    finding level-2 HTML links ... done

** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: package 'ggplot2' was built under R version 3.5.2
* DONE (EnhancedVolcano)
In R CMD INSTALL
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers`

`> EnhancedVolcano
function (toptable, lab, x, y, selectLab = NULL, xlim = c(min(toptable[, 
    x], na.rm = TRUE), max(toptable[, x], na.rm = TRUE)), ylim = c(0, 
    max(-log10(toptable[, y]), na.rm = TRUE) + 5), xlab = bquote(~Log[2] ~ 
    "fold change"), ylab = bquote(~-Log[10] ~ italic(P)), axisLabSize = 16, 
    pCutoff = 0.05, pLabellingCutoff = pCutoff, FCcutoff = 2, 
    title = "", titleLabSize = 16, transcriptPointSize = 0.8, 
    transcriptLabSize = 3, col = c("grey30", "forestgreen", "royalblue", 
        "red2"), colOverride = NULL, colAlpha = 1/2, legend = c("NS", 
        "Log2 FC", "P", "P & Log2 FC"), legendPosition = "top", 
    legendLabSize = 10, legendIconSize = 3, DrawConnectors = FALSE, 
    widthConnectors = 0.5, colConnectors = "black", cutoffLineType = "longdash", 
    cutoffLineCol = "black", cutoffLineWidth = 0.4, gridlines.major = TRUE, 
    gridlines.minor = TRUE, border = "partial", borderWidth = 0.8, 
    borderColour = "black") `

**Comment by kevinblighe** [comment]
That is unusual. Which version of R? Are you using Rstudio?

Could you try:
`devtools::install_github('kevinblighe/EnhancedVolcano', force = TRUE)`

Note `force = TRUE`

You may also consider restarting your computer and installing *EnhancedVolcano* as the ***very first*** thing that you do when you open the R session.

**Comment by seymoo** [comment]
> 
> 
> That is unusual. Which version of R? Are you using Rstudio?
> 
> Could you try:
> `devtools::install_github('kevinblighe/EnhancedVolcano', force = TRUE)`
> 
> Note `force = TRUE`
> 
> You may also consider restarting your computer and installing _EnhancedVolcano_ as the _**very first**_ thing that you do when you open the R session.

It worked! Just reset and installed firs thing in R, without FORCE=TRUE. 
Why was this restarting helped?
Many thanks.

**Comment by kevinblighe** [comment]
Hey, likely, it was that the cache of temporary files just needed to be cleared. I never leave a R session open when I am not using it, and I also restart my computer each day, when possible.
