### ISSUE TITLE
Error: Aesthetics must be either length 1 or the same as the data (1267): colour

### ISSUE THREAD

**Issue by 13479776** [kevinblighe/EnhancedVolcano#13]
When i use the colcustom, the error was happened.

Error: Aesthetics must be either length 1 or the same as the data (1267): colour
In addition: Warning message:
One or more P values is 0. Converting to minimum possible value...

**Comment by kevinblighe** [comment]
Hey, nice gravatar.

Can you show the commands that you are using with `colCustom`? To use `colCustom`, you will have to do some preparatory work prior to running `EnhancedVolcano(...)`.

There is an example here: https://github.com/kevinblighe/EnhancedVolcano#over-ride-colouring-scheme-with-custom-key-value-pairs

The warning message just indicates that you have p-values of 0 in your results table. This will be an issue, then, with the differential expression analysis tool that you have used.

**Comment by kevinblighe** [comment]
Hey, any follow up?

**Comment by kevinblighe** [comment]
Closed due to no response.
