### ISSUE TITLE
zero pvalues after lfcshrink

### ISSUE THREAD

**Issue by MichaelPeibo** [kevinblighe/EnhancedVolcano#14]
Hi,
Very nice function!
I tried to use res(from DESeq2) to do volcano plot, however, I found there is difference between lfcshrink and not shrinked. See below
[volcano indeFilter_F_lfcshrink.pdf](https://github.com/kevinblighe/EnhancedVolcano/files/3025229/volcano.TH%2BCB%2B.VS.TH%2BCB-.indeFilter_F_lfcshrink.pdf)
[volcano indeFilter_T_notlfcshrink.pdf](https://github.com/kevinblighe/EnhancedVolcano/files/3025230/volcano.TH%2BCB%2B.VS.TH%2BCB-.indeFilter_T_notlfcshrink.pdf)

Any suggestion which one I should represent for a publication-ready plot?
Thanks!

**Comment by kevinblighe** [comment]
Hey, this question may be better for the Bioconductor forum: https://support.bioconductor.org/t/Latest/

The lfc-shrunk fold changes look more realistic. However, I notice that you are also plotting the adjusted p-values on the y-axis? It may be better to plot the nominal p-values. Did you try that?

**Comment by kevinblighe** [comment]
Posted on Bioconductor: https://support.bioconductor.org/p/119564/

**Comment by MichaelPeibo** [comment]
Hi @kevinblighe 
Thanks for helping! Nominal p-values looks better!
Also I am confused some missing labels of 'red' gene points. https://github.com/kevinblighe/EnhancedVolcano/issues/5#issuecomment-478214805
Any suggestion? Thanks!

**Comment by kevinblighe** [comment]
Hey, those are most likely NA p-values. DESeq2 will set, to NA, the p-values for genes that have failed independentFiltering or cooksCutoff.

**Comment by MichaelPeibo** [comment]
Hi, I wonder whether those genes have biological meaning and I should check them or not; 
Or should I remove them by setting `na.rm=True` somewhere?

**Comment by kevinblighe** [comment]
Hey, this is a question unrelated to _EnhancedVolcano_. _EnhancedVolcano_ just plots the data that you provide to it. The genes that fail independentFiltering or cooksCutoff may have high variance, for whatever reason. You can remove them before using _EnhancedVolcano_, or you can just let the function automatically remove them (actually, it is the _ggplot2_ 'engine' that removes them).

**Comment by radlinsky** [comment]
> Hey, those are most likely NA p-values. DESeq2 will set, to NA, the p-values for genes that have failed independentFiltering or cooksCutoff.

Hello @kevinblighe I am also seeing missing labels, but in this case, the genes with missing labels have a non-NA s-value. It appears to randomly not plot a few gene labels, with no rhyme or reason?

**Comment by kevinblighe** [comment]
Hey radlinsky, yes, _EnhancedVolcano_ will only fit as many labels as it possibly can into the plot space. This prevents the figure from becoming 'over-crowded' with labels. Looking at your plot, you can likely fit more by setting `drawConnectors = TRUE`

Version 1.2.0 is the new version.
