### ISSUE TITLE
boxedlabels = TRUE doesn't work

### ISSUE THREAD

**Issue by swvanderlaan** [kevinblighe/EnhancedVolcano#15]
Hi,

First of all: what a great package!

Second, while applying it to my data, I wanted to use `boxedlabels = TRUE`, but this throws an error `Error in EnhancedVolcano(cells, lab = rownames(cells),  : 
  unused argument (boxedlabels = TRUE)`.

How can I fix that?

Sander

**Comment by kevinblighe** [comment]
Hey Sander, thank you for the kind words. The `boxedlabels` parameter is only available in the development branch, which you can install via:

`  devtools::install_github('kevinblighe/EnhancedVolcano')`

It will be part of the main Bioconductor release of _EnhancedVolcano_ in Bioc 3.9, which will be released at the end of April.

**Comment by swvanderlaan** [comment]
Ah, ok. Than I'll just wait ... Almost that time of year.

Thanks and keep up the good work. Seriously: great package.

**Comment by kevinblighe** [comment]
Cool! - thank you for the comments, Sander. You can check the full release schedule of Bioc 3.9 here: https://www.bioconductor.org/developers/release-schedule/

**Comment by kevinblighe** [comment]
Just a comment: the new version is now available through Bioconductor.
