### ISSUE TITLE
No Labels

### ISSUE THREAD

**Issue by lurens** [kevinblighe/EnhancedVolcano#16]
Hi Kevin
I would like to know if it is possible to completely remove the transcripts label.
I tried to put transcriptLabSize=0 but i still have labels (even if very small)
Thanks
Lorenzo
![Rplot](https://user-images.githubusercontent.com/13382631/55810199-777aea00-5ae7-11e9-961d-f3020099e5d7.png)

**Comment by kevinblighe** [comment]
Hey Lorenzo, thank you for using _EnhancedVolcano_

You should be able to switch off labels by specifying `lab = NA`

**Comment by lurens** [comment]
Thanks, it works.
Best
