### ISSUE TITLE
[bug?]class double problem

### ISSUE THREAD

**Issue by MatthewP-Newbee** [kevinblighe/EnhancedVolcano#21]
Hello, Thanks for such good tool.   
Here my problem is get error when I parse tibble with `double` class columns, see the code:
```R
> diff_expr_mt <- as.matrix(diff_expr)
> head(diff_expr, n=2L)
# A tibble: 2 x 7
  ENTREZID logFC AveExpr     t       P.Value adj.P.Val     B
     <dbl> <dbl>   <dbl> <dbl>         <dbl>     <dbl> <dbl>
1     1668  13.0    11.6  42.8 0.00000000297 0.0000475  8.74
2     1667  11.7    12.4  33.6 0.0000000142  0.000105   8.27
> head(diff_expr_mt, n=2L)
     ENTREZID    logFC  AveExpr        t      P.Value    adj.P.Val        B
[1,]     1668 12.95978 11.59565 42.78285 2.965640e-09 0.0000475481 8.735292
[2,]     1667 11.65022 12.37980 33.63170 1.421914e-08 0.0001046992 8.267310
> p <- EnhancedVolcano(diff_expr, x="logFC", y="P.Value", lab="ENTREZID", selectLab=NULL)
Error in EnhancedVolcano(diff_expr, x = "logFC", y = "P.Value", lab = "ENTREZID",  : 
  logFC is not numeric!
> p <- EnhancedVolcano(diff_expr_mt, x="logFC", y="P.Value", lab="ENTREZID", selectLab=NULL)
```  
However, `double` should be a `numeric`.
> It is a historical anomaly that R has two names for its floating-point vectors, double and numeric (and formerly had real).
> double is the name of the type. numeric is the name of the mode and also of the implicit class. As an S4 formal class, use "numeric".
> The potential confusion is that R has used mode "numeric" to mean ‘double or integer’, which conflicts with the S4 usage. Thus is.numeric tests the mode, not the class, but as.numeric (which is identical to as.double) coerces to the class.
> 
Also I want to know how to hide point labels? I use `selectLab=NULL` but still `ENTREZID` annotation on my plot. Thanks.

**Comment by kevinblighe** [comment]
Hey, the problem likely relates to the fact that you are using a tibble. If you just convert that to a data frame, it should run fine. The problem was recently reported on Biostars: https://www.biostars.org/p/380384/#380415

**Comment by kevinblighe** [comment]
I will leave this issue open for now. It will be addressed by the next Bioconductor release.

**Comment by kevinblighe** [comment]
Opened as a new issue by some other user: https://github.com/kevinblighe/EnhancedVolcano/issues/22
