### ISSUE TITLE
Add support for tibbles

### ISSUE THREAD

**Issue by dkulp2** [kevinblighe/EnhancedVolcano#22]
Suggest that you replace all references to [,x], [,y] and [,label] with [[x]], etc.
Tibbles don't drop by default, so they return single column tibbles with [,x] construct.
Using [[x]] will support tidyr programming as well as conventional data.frames.

**Comment by kevinblighe** [comment]
Thank you - this has now been implemented and will shortly be in the development branch of Bioconductor (and in the official release branch when Bioc 3.10 is released). I have added you to the ACKs, too. Thanks!

Kind regards,
Kevin
