### ISSUE TITLE
Hiding custom color legend

### ISSUE THREAD

**Issue by bmplaw** [kevinblighe/EnhancedVolcano#23]
legendVisible = FALSE does not hide the legend created for the custom key-value pairs

**Comment by kevinblighe** [comment]
Thanks - I will check this out. As a temporary solution, this will probably work:
`EnhancedVolcano(...) + theme(legend.position = 'none')`

**Comment by kingfabay** [comment]
Hi Kevin,
Thank you for the suggestion.

I also want to say that I am very new to R and your bioconductor tutorial
is very easy to follow. Thank you for providing such an useful package.

If you dont mind me asking, is there away to organise the order of custom
legend labels?

Thanks again.
Becker

**Comment by kevinblighe** [comment]
Hey Becker, thank you for the kind words. I think that it is possible to control the order of the custom legend. If you follow the example from the vignette, (here: https://github.com/kevinblighe/EnhancedVolcano#over-ride-colouring-scheme-with-custom-key-value-pairs ), then I think that you can control the order like this:

```
myvolcano <- EnhancedVolcano(
  ...,
  colCustom = keyvals,
  ...)

myvolcano + scale_color_manual(
  values=c(
    low="royalblue",
    Mid="black",
    high="gold"),
  labels=c(
    low='Lowest',
    Mid="Middle",
    high='Highest')))
```

So, that should order it as low -> Mid ->

For shape, it would be `+ scale_shape_manual(...)`
Does that make sense?

**Comment by kevinblighe** [comment]
Please re-open this issue if you still require help.

Kind regards,
Kevin
