### ISSUE TITLE
Cannot install "kevinblighe/EnhancedVolcano"

### ISSUE THREAD

**Issue by jahneldardavik** [kevinblighe/EnhancedVolcano#25]
Dear Kevin,
I have just discovered this package and wanted to have look at it. However, I immediately encounter a hurdle that I cannot figure out. When I do: devtools::install_github("kevinblighe/EnhancedVolcano"), I get the following return:
Downloading GitHub repo kevinblighe/EnhancedVolcano@master
√  checking for file 'C:\Users\jada\AppData\Local\Temp\RtmpktRGsc\remotes10b0795d3486\kevinblighe-EnhancedVolcano-b7aab27/DESCRIPTION' ...
-  preparing 'EnhancedVolcano':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'EnhancedVolcano_1.3.5.tar.gz'
   
* installing *source* package 'EnhancedVolcano' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'EnhancedVolcano'
* removing 'C:/Program Files/R/R-3.6.0/library/EnhancedVolcano'
* restoring previous 'C:/Program Files/R/R-3.6.0/library/EnhancedVolcano'
Error: Failed to install 'EnhancedVolcano' from GitHub:
  (converted from warning) installation of package ‘C:/Users/jada/AppData/Local/Temp/RtmpktRGsc/file10b07e1c68c7/EnhancedVolcano_1.3.5.tar.gz’ had non-zero exit status
> 

Hope you are able to advice me.
Thank you.
Jahn

**Comment by kevinblighe** [comment]
Hey Jahn,

I am not entirely sure what is happening there... I just installed it correctly on my computer using 
```
devtools::install_github("kevinblighe/EnhancedVolcano")
```
...however, I am using R 3.6.1.

The version of _EnhancedVolcano_ that are you are trying to install from GitHub was developed on my current computer under R 3.6.1, so, I think that, if you upgrade to £R 3.6.1, then it will work correctly.

Sorry, I know that it can be annoying to update the version of R... try to think of it as a 'Spring Clean'!

Kevin

**Comment by jahneldardavik** [comment]
Hi,
If I do not run the devtools thing and only do
“
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("EnhancedVolcano")
library(EnhancedVolcano)
“

it appears to work just fine.

Thanks
jahn
Fra: Kevin Blighe [mailto:notifications@github.com]
Sendt: 5. oktober 2019 01:39
Til: kevinblighe/EnhancedVolcano <EnhancedVolcano@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [kevinblighe/EnhancedVolcano] Cannot install "kevinblighe/EnhancedVolcano" (#25)


Hey Jahn,

I am not entirely sure what is happening there... I just installed it correctly on my computer using

devtools::install_github("kevinblighe/EnhancedVolcano")



...however, I am using R 3.6.1.

The version of EnhancedVolcano that are you are trying to install from GitHub was developed on my current computer under R 3.6.1, so, I think that, if you upgrade to £R 3.6.1, then it will work correctly.

Sorry, I know that it can be annoying to update the version of R... try to think of it as a 'Spring Clean'!

Kevin

**Comment by kevinblighe** [comment]
Thank you; however, that may not be installing the most updated version (?). Not to worry, can you confirm that you are now content with everything?

**Comment by jahneldardavik** [comment]
Appears good with me.
May have some newbie questions in due time. That said, your tutorial is great.
Thank you.

jahn

Fra: Kevin Blighe [mailto:notifications@github.com]
Sendt: 5. oktober 2019 19:41
Til: kevinblighe/EnhancedVolcano <EnhancedVolcano@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [kevinblighe/EnhancedVolcano] Cannot install "kevinblighe/EnhancedVolcano" (#25)


Thank you; however, that may not be installing the most updated version (?). Not to worry, can you confirm that you are now content with everything?

**Comment by kevinblighe** [comment]
Okay, sure thing! You can post the questions on Biostars, too: https://www.biostars.org/t/Open/

Kind regards,
Kevin

**Comment by dlinsen1** [comment]
I am having the same issue, but restart does not solve it. is it Rstudio? something else?
