### ISSUE TITLE
Numbers of Y-axis padj value 

### ISSUE THREAD

**Issue by Brandaoaf** [kevinblighe/EnhancedVolcano#27]
Dear Kevin Blighe, 

I would lie to know if it's possible to plot the numbers on the Y-axis according to the real padj value numbers from a DESeq2 data?
I used the following script code and the numbers of Y-axis (pCcutoffLine = 0.05) are not related to the real number of the padj value. 
Thank you so much.

EnhancedVolcano(SED.HFD.PGE_PA.HFD.PGE,
                lab = rownames(SED.HFD.PGE_PA.HFD.PGE),
                x = 'log2FoldChange',
                y = 'padj',
                xlim = c(-3, 4),
                ylim = c(0, 3),
                selectLab = c('FALSE'),
                title = 'SED.HFD.PGE_vs_PA.HFD.PGE',
                xlab = bquote(~ Log[2] ~ 'fold-change'),
                ylab = bquote(~ Adjusted ~p-value),
                cutoffLineType = 'twodash', 
                cutoffLineWidth = 0.6, 
                pCutoff = 0.05, 
                FCcutoff = 1.0, 
                transcriptPointSize = 2.5, 
                transcriptLabSize = 3, 
                boxedlabels = FALSE,
                col=c('grey0', 'green3', 'blue1', 'red2'), 
                colAlpha = 0.3, 
                shape = 20, 
                legend=c('Non-significant','Log2 fold-change','Adjust p-value','Adjust p-value & Log2 fold-change'),
                legendPosition = 'right',
                legendLabSize = 12,
                legendIconSize = 5.0,
                drawConnectors = FALSE, 
                widthConnectors = 1.0,
                colConnectors = 'black',
                gridlines.major = FALSE,
                gridlines.minor = FALSE)

#--------------# Volcano Plot #---------------------------#

![SED-HFD-PGE_PA-HFD-PGE_Volcano](https://user-images.githubusercontent.com/48332626/66439832-ca295600-e9e5-11e9-8d02-6f6dcbeb0ea8.png)

**Comment by kevinblighe** [comment]
Hey, the values in the column whose name is passed as the `y` parameter will be converted as follows:
`-log10(y)`

The value that you pass to `pCcutoffLine` will also be convereted in this same way.

Are you saying that you simply want to plot the p-values as they currently are? If this is what you want to do, then there is a workaround by passing 1/(10^y) for everything, e.g.:

```
p = 0.05
-log10(p)
[1] 1.30103
```

-log10(1/(10^p))
[1] 0.05

```

However, the package code is not quite designed for that.

**Comment by Brandaoaf** [comment]
> 
> 
> Hey, the values in the column whose name is passed as the `y` parameter will be converted as follows:
> `-log10(y)`
> 
> The value that you pass to `pCcutoffLine` will also be convereted in this same way.
> 
> Are you saying that you simply want to plot the p-values as they currently are? If this is what you want to do, then there is a workaround by passing 1/(10^y) for everything, e.g.:
> 
> ```
> p = 0.05
> -log10(p)
> [1] 1.30103
> 
> 
> -log10(1/(10^p))
> [1] 0.05
> ```
> 
> However, the package code is not quite designed for that.

**Comment by Brandaoaf** [comment]
Dear Kevin, 
Thank you so much for all help. In fact, after your explanation, I realize the lack of -Log10 in the Y-axis label. 
So, the data and analysis are correct. I have just to correct the Y-axis label.
Thank you.

**Comment by kevinblighe** [comment]
Sure thing! - no problem.
