### ISSUE TITLE
[request]drawConnectors alway on or pinpoint dots

### ISSUE THREAD

**Issue by sunta3iouxos** [kevinblighe/EnhancedVolcano#28]
Hi Kevin,
Thank you for the enhanced volcanoPlot wrapper.

I am font of the
drawConnectors and selectLab options.
but there are plots that the genes of interest are quite sparse and can not be highlighted in the pool of dots.
Is there a possibility to:
1. make the drawConnectors always on even there is no overlap?
2. create a circle/square on the point of interest?
3. make use of specific shape for some of the genes?
4. I also tried the shapeCustom but I was not managed to make it work (do you have an examble?).

regarding 3 I tried to do something like [that](https://github.com/kevinblighe/EnhancedVolcano#over-ride-colour-andor-shape-scheme-with-custom-key-value-pairs) but couldn't
my code:

```
EnhancedVolcano(toptable = res.tables[[1]],
                lab = res.tables[[1]][, 'SYMBOL'],
                x = 'log2FoldChange',
                y = 'padj',
selectLab = c("Hdac6", "Mcm10", "Mcm8", "Krt14", "Rbm20", "Kras", "Cdkn2a", "Ccndf", "Chaf1b", "Pola2", "Mrm3", "Rad50", "Cdkn3", "Mettl21e", "Igfbp2", "hopx", "Sftpc", "Cdh1", "apln", "Pecam", "Cdh5","Cdkn3","Ccnf","Foxo3","Ccnd","YWHAE","SIRT1","Rbl1","Ccnb1","bcl6","Gadd45a","Cat","SOD2","Cdkn2a","Cdkn1d","PLK1","TNFSF10"),

                xlab = bquote(~Log[2]~ 'fold change'),
                ylab = bquote(~-Log[10]~adjusted~italic(P)),
                title = 'P21_SD versus P21_HFD, padj= 0.05, FC = 2',
                xlim=c(-6.5,5),
                pCutoff = 0.05,
                FCcutoff = 1.0,
                pointSize = 1.0,
                labSize = 5,
                col=c('grey60', 'green', 'grey70', 'red'),
                colAlpha = 4/5,
                drawConnectors = TRUE,
                widthConnectors = 0.5,
                lengthConnectors = unit(0.01, 'npc'),
                colConnectors = "black",
                )

```
![Rplot05](https://user-images.githubusercontent.com/20404754/67090231-db265400-f1a9-11e9-8e46-b0283c9b5c3c.png)

**Comment by kevinblighe** [comment]
Hey, thank you for using the package, and my apologies for the delay in responding.

> make the drawConnectors always on even there is no overlap?

This is not possible at present. Basically, the assumption is that the end-user wants to fit as many labels as possible, in whatever way possible. So, the internal algorithms will make use of connectors where possible. It would involve a considerable change to the code, I believe.

Perhaps if you use `boxedLabels = TRUE`, then it will draw an arrow / connector for everything, but then there may be too much information in the plot space.

> create a circle/square on the point of interest?

The closest to having this functionality is this section from the vignette: https://github.com/kevinblighe/EnhancedVolcano#shade-certain-variables

However, that is shading the points - is that sufficient? The intensity of the shade can be controlled with `shadeAlpha`

> make use of specific shape for some of the genes?
> I also tried the shapeCustom but I was not managed to make it work (do you have an examble?).

I see... were you able to reproduce this part in the vignette (the part to which you link)?

**Comment by kevinblighe** [comment]
Closed as no response for 2 weeks. Please re-open if this is still an issue
