### ISSUE TITLE
Gene label plotting

### ISSUE THREAD

**Issue by Deusu** [kevinblighe/EnhancedVolcano#29]
Hi Kevin,
thanks for the amazing package!

I recently moved to iOS and updated the package to 1.4.0 but I'm facing some issues when plotting gene labels.
The dot is correctly recognised on the plot but instead of being labeled with the gene name is instead labeled with a 4 digit number. Interestingly, the numbers seem to be specific for each gene and never change (ever after R session restart) but I can't find any reference for those numbers in my dataframe.

`EnhancedVolcano(toptable = dataframe, 
                                 lab = dataframe$gene_name,
                                 x = 'log2FoldChange',
                                 y = 'padj',
                                 selectLab = c("CLEC6A", "IL23A", "SLPI", "WNT9A", "MT1H", "MT1M")
                                 )`

![Volcano01](https://user-images.githubusercontent.com/57913461/69133497-4c616b80-0ab6-11ea-92e5-bf9945b79c6c.png)

Interestingly, if I skip the `selectLab` option, all the gene labels are plotted with the correct names.

`EnhancedVolcano(toptable = dataframe, 
                                 lab = dataframe$gene_name,
                                 x = 'log2FoldChange',
                                 y = 'padj'
                                 )`

![Volcano02](https://user-images.githubusercontent.com/57913461/69133515-52efe300-0ab6-11ea-9794-0a0a4bc1da37.png)

Any clue of which might be the problem?

Thanks a lot!
Marco

> sessionInfo()
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.6
>
> attached base packages:
> parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> pander_0.6.3                RColorBrewer_1.1-2          EnhancedVolcano_1.4.0       ggrepel_0.8.1               ggplot2_3.2.1  pheatmap_1.0.12             edgeR_3.28.0                DESeq2_1.26.0               SummarizedExperiment_1.16.0 DelayedArray_0.12.0. BiocParallel_1.20.0         matrixStats_0.55.0          Biobase_2.46.0              GenomicRanges_1.38.0        GenomeInfoDb_1.22.0       IRanges_2.20.0              S4Vectors_0.24.0            BiocGenerics_0.32.0         Vennerable_3.1.0.9000       limma_3.42.0

**Comment by kevinblighe** [comment]
Hey Marco, thank you for using this package.

hmm... I am wondering if `dataframe$gene_name` is encoded as a categorical variable? Can you check this via:
```
str(dataframe)
```
?

**Comment by Deusu** [comment]
Hi, thanks for the prompt reply!

Yes, the column is encoded as "factor", I guess the package requires a string.
If I just convert the column to "character" everything works perfectly!

Thanks a lot for the help!
Marco

**Comment by kevinblighe** [comment]
Okay, great! Grazie / thank you
