### ISSUE TITLE
Deprecated pointSize, labSize args in vignette?

### ISSUE THREAD

**Issue by cgpu** [kevinblighe/EnhancedVolcano#30]
Hi Kevin, 

Thank you for this R package!

I am running the vignette and I got the following error message:

```
Error in EnhancedVolcano(res2, lab = rownames(res2), x = "log2FoldChange",  : 
  unused arguments (pointSize = 4, labSize = 3)
```
![image](https://user-images.githubusercontent.com/38183826/69330226-72b81000-0c4a-11ea-8842-0d140325e28b.png)

Once I remove the arguments `pointSize, labSize ` from the `EnhancedVolcano::EnhancedVolcano()` function everything works ok.

https://github.com/kevinblighe/EnhancedVolcano/blob/master/vignettes/EnhancedVolcano.Rmd#L152-L153

EDIT:

Also occurs for the following args:

- [ ] `boxedLabels`
- [ ] `labCol`
- [ ] `labFace`

**Comment by kevinblighe** [comment]
Hey, thanks for using this package. Can you confirm the version that you are using?

The vignette will always reflect the most updated version (v1.4). In the most recent release, I made some changes to parameter names, but they should be backward compatible. It seems that you may be using a version pre- version 1.2?

**Comment by cgpu** [comment]
> Hey, thanks for using this package. Can you confirm the version that you are using?
> 
> The vignette will always reflect the most updated version (v1.4). In the most recent release, I made some changes to parameter names, but they should be backward compatible. It seems that you may be using a version pre- version 1.2?

Thanks for such a prompt response - my `sessionInfo()` says I have 1.2

![image](https://user-images.githubusercontent.com/38183826/69348822-b45ab200-0c6e-11ea-81be-97ee3b1e4b7c.png)

**Comment by kevinblighe** [comment]
Great - thank you! You may need to update your R, too, if you want to avail of the later versions.

**Comment by cresbioinfo** [comment]
Dear Kevin, 
I tried installing the package using Biocmanager and it's not getting updated to the recent version. Everytime I try to download it, only the v1.2.0 is getting installed

**Comment by kevinblighe** [comment]
You are likely using an old version of R. Please update R.
