### ISSUE TITLE
How to add break y-axis?

### ISSUE THREAD

**Issue by bhuwankhatri11** [kevinblighe/EnhancedVolcano#31]
My y-axis values range from 0 to about 300. Is it possible to break y-axis; may be from 50-175 so that it enlarges image from 0-50 ?

**Comment by kevinblighe** [comment]
Hey, that is not currently possible, but may be in future versions. My recommendation for now would be to show 2 volcano plots side by side:

- the complete volcano
- a focused volcano on the region of interest (use `xlim` and `ylim`)

**Comment by kevinblighe** [comment]
Closed due to no response

**Comment by vizzerra** [comment]
Hey Kevin. Was this ever implemented? Many thanks!

**Comment by junli1988** [comment]
I have the same question. I tried adding a ggbreak to the plot, but that didn't work out well
