### ISSUE TITLE
error message when using multiple shapes

### ISSUE THREAD

**Issue by yeroslaviz** [kevinblighe/EnhancedVolcano#32]
When using my own data,  I keep getting stuck when I want to use multiple shapes.

the command I sue is this 

```
EnhancedVolcano(resMA,
    lab = rownames(resMA),
    x = 'log2FoldChange',
    y = 'pvalue',
    selectLab = c('ENSG00000180537','ENSG00000153885'),
    xlim = c(-6,7),
    xlab = bquote(~Log[2]~ 'fold change'),
    pCutoff = 10e-14,
    FCcutoff = 2.0,
    pointSize = 4.0,
    labSize = 5.0,
    shape = c(1,4,23,25), 
    colAlpha = 1,
    legendPosition = 'right',
    legendLabSize = 14,
    legendIconSize = 5.0)
```

and this is the error I get:

```
Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NS = 1, FC = 4, P = 23, : replacement has 4 rows, data has 3
17. stop(sprintf(ngettext(N, "replacement has %d row, data has %d", "replacement has %d rows, data has %d"), N, nrows), domain = NA)
16. `[[<-.data.frame`(`*tmp*`, i, value = c(NS = 1, FC = 4, P = 23, FC_P = 25))
15. `[[<-`(`*tmp*`, i, value = c(NS = 1, FC = 4, P = 23, FC_P = 25 ))
14. modify_list(data, guide$override.aes)
13. FUN(X[[i]], ...)
12. lapply(layers, function(layer) { matched <- matched_aes(layer, guide, default_mapping) if (length(matched) > 0) { if (!is.null(names(layer$show.legend))) { ... 11. guide_geom.legend(X[[i]], ...)
10. FUN(X[[i]], ...)
9. lapply(gdefs, guide_geom, layers, default_mapping)
8. vapply(x, is.null, logical(1))
7. compact(lapply(gdefs, guide_geom, layers, default_mapping))
6. guides_geom(gdefs, layers, default_mapping)
5. build_guides(plot$scales, plot$layers, plot$mapping, position, theme, plot$guides, plot$labels)
4. ggplot_gtable.ggplot_built(data)
3. ggplot_gtable(data)
2. print.ggplot(x)
1. (function (x, ...) UseMethod("print"))(x)
```

Whan I remove the row `shape = c(1,4,23,25), ` the command works.

What is the meaning of the error?

thanks

Assa

**Comment by yeroslaviz** [comment]
Ok, 

I have found the problem. It was because I wanted to see only the two genes in the `selectLab` option, so that i couldn't get four different groups for the `shape` parameter. 
This might need a more clearer error message, that if the selected IDs are not in the output, it causes an error.

**Comment by kevinblighe** [comment]
Hey, thank you for leaving this error message. I am still not sure what happened. The `shape` parameter should work just fine with `selectLab`, as shown here: https://github.com/kevinblighe/EnhancedVolcano#only-label-key-variables

Are you saying that 'ENSG00000180537' and 'ENSG00000153885' are not even in your data?

**Comment by kevinblighe** [comment]
Please respond again if you still have an issue

**Comment by sme229** [comment]
Hi Kevin, I have the same issue and wasn't able to resolve yet:
Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NS = 6, FC = 6, P = 6,  : 
  replacement has 4 rows, data has 3

Could you please help?

**Comment by Nihilecas** [comment]
> Hi Kevin, I have the same issue and wasn't able to resolve yet: Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NS = 6, FC = 6, P = 6, : replacement has 4 rows, data has 3
> 
> Could you please help?

I have encountered the same issue and error as sme229. I was not able to solve it directly, but I have found a workaround.

The problems originates from an empty group which no shape can be assigned to.
EnhancedVolcano groups your data into 4 categories depending on whether they meet the thresholds set for FC and p-value: FC+/p+, FC-/p+, FC+/p-, and FC-/p-. Most large datasets are likely to contain at least one datapoint that falls into each category. But if one of the four groups is empty in your dataset, you will get an error when trying to assign shapes to the four groups.

**The workaround is to introduce a dummy value into the dataset that fills the missing group**. To prevent actual plotting of the dummy value on the resulting Volcanoplot you can use NA for its shape:  shape = c(1, 2, NA, 4) or similar. The downside of this workaround is that it will show up in the legend, but this can be fixed manually if necessary.
