### ISSUE TITLE
y-axis

### ISSUE THREAD

**Issue by paytonyau** [kevinblighe/EnhancedVolcano#33]
It is possible to change y-axis from -log10, to another method, such as log2 or just simply from 0 to 1? 
This is because in proteomics data, confidence (from 0 to 100%) is some ways more reliable than p-value.

**Comment by kevinblighe** [comment]
Hey, the package really is designed for the standard differential expression analyses and the standard volcano plot. However, there is an indirect way around this: Basically, you could create a new column in your input data that represents the inverse of the anti-logarithm of the p-values [or whatever data that you are plotting]. In this way, the internal `-log10` calculation performed by `EnhancedVolcano()` is nullified:

`res$pvalue_new <- 1/(10^res$pvalue)`

You will face 'battles' elsewhere with the internal code of the function, though. It may be better to simply pull some code from the online forums, and edit it for your own needs.
