### ISSUE TITLE
Legend Labels not changing

### ISSUE THREAD

**Issue by athulmenon** [kevinblighe/EnhancedVolcano#34]
Hi Kevin,

Thank you for this great tool.

I am facing an issue while trying to change the legend names. I am recieving the below error when I tried to change it. Here is my code.

`EnhancedVolcano(result,
                 lab = result$Gene,
                 x = "log2Ratio",
                 y = "pvalue",
                 pCutoff = 0.05,
                 FCcutoff = 1.5,
                 labSize = 2.5,
		 legend = c("A","B","C","D"),
                 xlab = bquote(~Log[2]~ 'Ratio'),
                 shape = c(6, 6, 19, 16),
                 title = "Volcano Plot",
                 subtitle = "Changes",
                 caption = "Log2Ratio cutoff - 1.5; p-value cutoff - 0.05",
                 legendPosition = "bottom",
                 legendLabSize = 14,
                 col = c("grey30", "forestgreen", "royalblue", "red2"),
                 colAlpha = 0.9,
                 drawConnectors = TRUE,
                 hline = c(10e-8),
                 widthConnectors = 0.5)`

Error is as below.

> Error in EnhancedVolcano(result, lab = result$Gene, x = "log2Ratio", y = "pvalue",  : 
  argument 8 matches multiple formal arguments

Even I am not able to see the legends changed in your tutorial vignettes also.

Thanks,
Athul

**Comment by kevinblighe** [comment]
Hey Athul, thank you for using this package. Which version [of the package] are you using? The new way to set legend labels is via `legendLabels`
