### ISSUE TITLE
Adding label to the cutoff vline

### ISSUE THREAD

**Issue by Aanchal85** [kevinblighe/EnhancedVolcano#36]
I had been trying to add a label of cutoff by using the command - 
vline=c(-6, 6),label = c(-6,6),
but it says unused argument and nothing happens to the plot labels. Any help regarding this? 
Thank you.

**Comment by kevinblighe** [comment]
Hey, I think that you can do this via `geom_text(...)`. I give an example in the vignette for one of my other Bioc packages (scroll down a bit to the Scree plot):
https://github.com/kevinblighe/PCAtools#determine-optimum-number-of-pcs-to-retain

**Comment by kevinblighe** [comment]
Let me know if that works (or not).
