### ISSUE TITLE
pointSize unused argument

### ISSUE THREAD

**Issue by eoinmck** [kevinblighe/EnhancedVolcano#37]
Dear Kevin,

Firstly, many thanks for a great package. I've been experiencing an issue similar to that noted by others, namely that the pointSize, labSize and boxedLabels options result in an 'unused argument' error:

p1 <- EnhancedVolcano(p,
                      lab = rownames(p),
                      x = 'log2FC',
                      y = 'padj',
                      xlim = c(-2,2.5),
                      ylim = c(0,3),
                      pointSize = 4)

Error in EnhancedVolcano(lab = p$labs, x = "log2FC", y = "padj", xlim = c(-2,  : 
  unused argument (pointSize = 4)

I noticed that previous errors were related to outdated versions of either the package or R, but I don't think that is the issue here (I've installed the latest version from Github, rather than via Bioconductor):

platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.0                         
year           2019                        
month          04                          
day            26                          
svn rev        76424                       
language       R                           
version.string R version 3.6.0 (2019-04-26)

> packageVersion("EnhancedVolcano")
[1] ‘1.5.4’

I'd be grateful for any suggestions on what might be tripping the options up.

Many thanks again for a great package and best wishes

**Comment by kevinblighe** [comment]
Hey, sorry about that. You are using an old version of the package. I decided to change some of the parameter names in the last release, a few months ago. For your version, I think that `transscriptPointSize` will work.

**Comment by eoinmck** [comment]
Many thanks Kevin - that worked without problems.

Thanks again for your work on the package and best wishes



On 28 Mar 2020, at 17:00, Kevin Blighe <notifications@github.com<mailto:notifications@github.com>> wrote:



Hey, sorry about that. You are using an old version of the package. I decided to change some of the parameter names in the last release, a few months ago. For your version, I think that transcriptPointSize will work.
