### ISSUE TITLE
About Legend

### ISSUE THREAD

**Issue by JJSGouveia** [kevinblighe/EnhancedVolcano#38]
Hi Kevin,

Thank you for this tool.

I am using the Enhanced Volcano package and perceived that adding "legend=c('A','B,'C','D')" as indicated in the item 4.5 of vignette (https://www.bioconductor.org/packages/release/bioc/vignettes/EnhancedVolcano/inst/doc/EnhancedVolcano.html#draw-labels-in-boxes) does not generate the expected in the plot.

Despite of this, adding "legendLabels=c('A','B,'C','D')" creates the plot with the expected information.

Thanks for the attention,

Joao Gouveia

**Comment by kevinblighe** [comment]
Hey João, thank you for noticing that! It will be updated when the next version of Bioconductor is released.

In the GitHub vignette, it has already updated:
https://github.com/kevinblighe/EnhancedVolcano#adjust-legend-position-size-and-text

Obrigado! / Thanks!
