### ISSUE TITLE
Shade (annotate) part of the plot

### ISSUE THREAD

**Issue by zx8754** [kevinblighe/EnhancedVolcano#4]
See relevant post at SO:

https://stackoverflow.com/questions/53272541/how-do-i-shade-plot-subregion-and-use-ggrepel-to-label-a-subset-of-data-points

**Comment by zx8754** [comment]
I meant to ask if this package has this feature, maybe worth adding?

**Comment by kevinblighe** [comment]
Ah, yes and no. I will leave this issue open and add the feature to the next version! Will add you to ACKs.

**Comment by kevinblighe** [comment]
I have added very basic functionality for this in https://github.com/kevinblighe/EnhancedVolcano/commit/f6e8ea696567735887fcf3d3ff734577c1462f9b

Also see the final example in the vignette at https://github.com/kevinblighe/EnhancedVolcano#shade-certain-transcripts

This can be elaborated further in the future if the feature is used.

Thanks!
