### ISSUE TITLE
error with ggplotly

### ISSUE THREAD

**Issue by kengcher** [kevinblighe/EnhancedVolcano#40]
Hi 

I am trying to use enhanced volcano on shiny but i get this error:

> p <- EnhancedVolcano(gene_diff, lab = gene_diff$symbol, x = 'logfc', y = 'pval')
> class(p)
[1] "gg"     "ggplot"
> p %>% ggplotly(tooltip = "tooltip")
Error in unique.default(x) : unique() applies only to vectors
In addition: Warning messages:
1: In if (nchar(axisTitleText) > 0) { :
  the condition has length > 1 and only the first element will be used
2: In if (nchar(axisTitleText) > 0) { :
  the condition has length > 1 and only the first element will be used

i can see the plot in R studio but not when trying to visualize it in shiny.

Thank you.

**Comment by kevinblighe** [comment]
Hey, can you try the new version that has just been released with R v4.0.0 and Bioconductor 3.11?

**Comment by kevinblighe** [comment]
Got this working? I have never yet checked how the package functions in R Shiny...

**Comment by kevinblighe** [comment]
No response
