### ISSUE TITLE
incorrect p-val cutoff line render

### ISSUE THREAD

**Issue by AminMahpour** [kevinblighe/EnhancedVolcano#41]
Hi EnhancedVolcano developers
 
I noticed that by default the EnhancedVolcano plot renders the p-value cutoff dotted line below the indicated cutoff value. I am just wondering if this behavior is by design or a bug?

Thanks,
Amin

**Comment by kevinblighe** [comment]
Hey, thanks for using this package.

Are you sure? Can you provide a reproducible example?

The code that generates the line is this:
https://github.com/kevinblighe/EnhancedVolcano/blob/master/R/EnhancedVolcano.R#L505

So, if it looks out of place, it could be one of these possibilities:
- plot rendering issue

- non-numeric value is passed as _pCutoff_, which is somehow automatically converted to float or integer

- bug in ggplot2


Kevin

**Comment by kevinblighe** [comment]
No response
