### ISSUE TITLE
dealing with zero pvalue

### ISSUE THREAD

**Issue by MichaelPeibo** [kevinblighe/EnhancedVolcano#43]
Hi @kevinblighe 
I am using MAST to calculate scRNA-seq data.
For top DEGs, there are extreme small pvalues(0.000000e+00),  figure below.
They will not be on the volcanoplot. Any suggestion how to plot them?
![image](https://user-images.githubusercontent.com/32219336/81936179-6a062c80-9624-11ea-8817-83247d5df61f.png)

**Comment by kevinblighe** [comment]
Hey Michael, the package should convert these to 10^-1 times the lowest non-zero p-value, and issue a warning message in doing so. Does that not happen in your case? Which version of the package are are you using?

You can see this elaborated in the following code chunk:
https://github.com/kevinblighe/EnhancedVolcano/blob/master/R/EnhancedVolcano.R#L91-L111

Let me know!

**Comment by MichaelPeibo** [comment]
@kevinblighe  Yes, you are right. I did not see it because I set a xlim and ylim. When I removed or enlarge them, I could see them now.
Great package!

**Comment by kevinblighe** [comment]
Great! - thanks @MichaelPeibo

**Comment by wdg118** [comment]
Yeah I've had a similar issue and it doesn't fix this. I did the same thing as @MichaelPeibo and had a ton of these values, went to label top 20 up and top 20 down regulated genes using selectLab but this issue with the zeroes is preventing that. I can't even manually input gene names. This is frustrating.
