### ISSUE TITLE
p-value or adjusted-p-value

### ISSUE THREAD

**Issue by Homap** [kevinblighe/EnhancedVolcano#44]
Hello,

Thank you for the fantastic package. 

I was wondering whether the function uses p-values or adjusted p-values? Is adjusted p-value threshold determined by `pLabellingCutoff` argument?

Thank you again,
Homa

**Comment by kevinblighe** [comment]
Hey Homa. The user can choose to plot nominal (un-adjusted) or adjusted p-values by selecting a different column name from the input results table.

The value of `pLabellingCutoff` will always be applied indiscriminately as `-log10(pLabellingCutoff)`, irrespective of the nature of the input p-values.

**Comment by Homap** [comment]
Thank you so much.

**Comment by kevinblighe** [comment]
Sure thing!
