### ISSUE TITLE
Issue when trying to shade a key variable

### ISSUE THREAD

**Issue by AnthonyDohertyTCD** [kevinblighe/EnhancedVolcano#45]
Not sure if this is the correct location for my question.

Has anyone come across this error before. My key variable is not being shaded and I get this error message: 

Computation failed in `stat_density2d()`:
missing value where TRUE/FALSE needed. 

New to R but have been able to make some nice plots with this excellent package!

Thank you.

**Comment by kevinblighe** [comment]
Hi Anthony, did you post on Biostars, too?

I have not seen this error previously. Can you show me the code that you use to run `EnhancedVolcano()`?

**Comment by AnthonyDohertyTCD** [comment]
Yes sorry for posting twice was not sure the best place to ask. 

I am using standard output from the DeSeq2 res command. I am trying to make a key variable MYC stand out more. I have been able to overwrite the colour scheme and change the shape of this variable alone also (see attached PDF). I would like it to stand out more. Hence why I would like to shade it.
[ExampleVolcano.pdf](https://github.com/kevinblighe/EnhancedVolcano/files/4734714/ExampleVolcano.pdf)

```
#Adding Custom Colours
keyvals <- ifelse(
  res$log2FoldChange < -log2(1.5) & res$padj < (0.05), 'royalblue',
  ifelse(res$log2FoldChange > log2(1.5) & res$padj < (0.05), 'red',
         'black'))


keyvals[is.na(keyvals)] <- 'black'
names(keyvals)[keyvals == 'red'] <- 'high'
names(keyvals)[keyvals == 'black'] <- 'mid'
names(keyvals)[keyvals == 'royalblue'] <- 'low'


#Making 2 variables a different shape to stand out
# define different cell-types that will change shape
celltype1 <- c('ENSG00000136997')
celltype2 <- c('ENSG00000007516')


# create custom key-value pairs for different cell-types
# this can be achieved with nested ifelse statements
keyvals.shape <- ifelse(
  rownames(res) %in% celltype1, 11,
  ifelse(rownames(res) %in% celltype2, 1,
         1))
keyvals.shape[is.na(keyvals.shape)] <- 1
names(keyvals.shape)[keyvals.shape == 1] <- "All other genes"
names(keyvals.shape)[keyvals.shape == 11] <- 'MYC'
names(keyvals.shape)[keyvals.shape == 1] <- NULL

#Define variable to be shaded
celltype3 <- c('ENSG00000132688')

#Enhanced volcano plot 
library(EnhancedVolcano)
EnhancedVolcano(res, lab = rownames(res),
                x = 'log2FoldChange', y = 'padj',
                selectLab = celltype1, xlim = c(-10, 10), xlab = bquote(~Log[2]~ 'fold change'), 
                ylab = bquote(~-Log[10]~adjusted~italic(P)),
                pCutoff = 0.05, FCcutoff = log2(1.5), pointSize =  c(ifelse(rownames(res) %in% c('ENSG00000136997') , 5, 1)), labSize = 3.0, colAlpha = 5 ,colCustom = keyvals, shapeCustom = keyvals.shape,
                labCol = 'black',
                labFace = 'bold',
                boxedLabels = T,
                gridlines.major = FALSE,
                gridlines.minor = FALSE,
                shade = celltype3,
                shadeLabel = 'MYC',
                shadeAlpha = 1/2,
                shadeFill = 'purple',
                shadeSize = 4,
                shadeBins = 5,
                legend=c('NS', 'Log2 FC', 'Adjusted p-value', 'Adjusted p-value & Log2 FC'))

```

The above attached PDF is produced but with the following warning and no shading. 
Warning message:
Computation failed in `stat_density2d()`:
missing value where TRUE/FALSE needed 

Thank you for the quick reply.

**Comment by kevinblighe** [comment]
Thanks for sharing. Can you confirm your version of R and also this package? A change brought about in R 4.0.0 has already caused functionality to change across many packages.

Also, is this line necessary?
`names(keyvals.shape)[keyvals.shape == 1] <- NULL`

The 'shade' functionality is a part of the package that I have considered removing, as I am not overly content with it. If you are just looking to highlight your gene, _ENSG00000132688_, is the `selectLab` and `boxedLabels` functionality enough?

`selectLab` and `boxedLabels` should work together, though, as exemplified here:
https://github.com/kevinblighe/EnhancedVolcano#shade-certain-variables

**Comment by AnthonyDohertyTCD** [comment]
R version 3.6.3 (2020-02-29)

packageVersion("EnhancedVolcano")
‘1.4.0’

That line was not necessary thank you. 

I have used the selectLab and boxedLabels together and it works very well. I would have  liked to highlight it a bit more. Instead of shading, would it be possible to colour this key variable alone a single colour while also maintaining my custom colour scheme. 

Thank you again for the help. I am new to R as I said and this package has been quite easy to use. 

Yes the variable I am trying to shade is for sure in my data.

**Comment by kevinblighe** [comment]
I'm not sure what else to suggest. If possible, upgrade to R 4.0.0, which will in turn pull in the 'newest' version of _EnhancedVolcano_, too.

You could also try to paste a mini-table here that acts as a reproducible example that I can debug here. Or, feel free to email me some data if you prefer to keep the data private.

**Comment by AnthonyDohertyTCD** [comment]
That would be cool if I could email you. In regards to my last comment: Instead of shading, would it be possible to colour this key variable alone a single colour while also maintaining my custom colour scheme.

Thanks again for all the help.

**Comment by kevinblighe** [comment]
You should be able to label it its own colour via the `colCustom `argument, which works much the same as `shapeCustom`. Also take a look at the example here, where you could change the size of point for the key gene:
https://github.com/kevinblighe/EnhancedVolcano#highlighting-key-variables-via-custom-point-sizes

**Comment by kevinblighe** [comment]
Hey @AnthonyDohertyTCD , this has now been implemented. You'll have to install the GitHub version for now; otherwise, in a few days, it will be on the Bioconductor Devel branch (and official branch when the next version of Bioconductor is released).

An example here:
https://github.com/kevinblighe/EnhancedVolcano#shade-certain-variables
