### ISSUE TITLE
advice on LFC cutoff

### ISSUE THREAD

**Issue by klai001** [kevinblighe/EnhancedVolcano#46]
Hi Kevin
thanks for developing the EV.
was wondering if you recommend a cut off for LFC for values that are shrunk?
my values are shrunk and in your vigentte you mentioned that LFC |1.5| is too stringent
that's true because i cant see any labels appearing with LFC 1.5
how do we determine the LFC for shrunk values and what's your recommendation?
thanks

**Comment by kevinblighe** [comment]
Hey @klai001, yes, the shrinkage can drastically reduce the fold-change. I think that it is okay to reduce the cut-off to absolute 1. As these are log scale, at a cut-off of even 1, the change is appreciable.

**Comment by kevinblighe** [comment]
Please re-open if there is still any doubt!
