### ISSUE TITLE
Can natural log (not Log2FC) also be used equally well?

### ISSUE THREAD

**Issue by CodeInTheSkies** [kevinblighe/EnhancedVolcano#49]
Hi Kevin,

I just came across your package, and am about to try it.  Looks very exciting!  Before that, I just wanted to double check the following.  My DE list is actually from single-cell data, specifically from the Seurat package.  Therefore, they are not log2-based FCs, but rather based on the natural log.  Does this matter in any way?  As far as I can see, it shouldn't, but I wanted to ask you, is the package more optimal for Log2FCs in any way?  Hope I can still benefit from the package!

Also, are there any points/tips to keep in mind when using the package for single-cell data?

Many thanks!

**Comment by kevinblighe** [comment]
Hey, yes, you can technically use any type of fold change, even linear (unlogged) fold changes. You would obviously have to change the x-axis legend, though!

Kevin
