### ISSUE TITLE
Removed 351 rows containing missing values (geom_point)

### ISSUE THREAD

**Issue by prasidda** [kevinblighe/EnhancedVolcano#5]
Hi Kevin,

Your package works well for most of what I am trying to do. But I keep getting the following error when I try to make the volcano plot:
"Warning message:
Removed 351 rows containing missing values (geom_point)"
It doesn't seem to be a problem with the axes limits as I changed both of them to accommodate the max and min of both variables. Any idea what might be causing this problem? Thanks!

**Comment by kevinblighe** [comment]
Hey prasidda, thank you for using _EnhancedVolcano_! What is the source of your data? Do you know if it the test statistics contain missing or infinite values? Some statistical tests will return 'NA' or 'Inf' for genes for which no accurate model can be fit.

**Comment by kevinblighe** [comment]
I have made changes and these warning messages should no longer appear. They are produced when there are NAs in your data.

Commit: https://github.com/kevinblighe/EnhancedVolcano/commit/f6e8ea696567735887fcf3d3ff734577c1462f9b

**Comment by prasidda** [comment]
Thanks, Kevin. I did realize that it was indeed NAs in my data giving this error. I was using DeSeq2 data and didn't expect there to be NAs in the p-value column, but there were quite a few when I checked.

**Comment by kevinblighe** [comment]
No problem. To avail of the new code, you will have to wait until the next Bioconductor release or else downloading the development version of the package via:
`devtools::install_github("github.com/kevinblighe/EnhancedVolcano/")`

**Comment by MichaelPeibo** [comment]
Hi @prasidda @kevinblighe 
I have some labels not shown gene symbol or id on the plots, is this due to NAs?
![image](https://user-images.githubusercontent.com/32219336/55272775-ac738980-52fc-11e9-8848-cfcd1d900d01.png)
