### ISSUE TITLE
Question - How is the number of labels plotted decided?

### ISSUE THREAD

**Issue by northNomad** [kevinblighe/EnhancedVolcano#50]
As titled,

If the plot has, say, 1000 genes that meet the criteria to be labelled:

Which of the 1000 genes are labelled? 
I know that some genes are not labelled to avoid overplotting.

I am wondering how it is decided which genes are plotted and which are not.

Also, I can not yet find a way to label, lets say, top 20 genes with the highest LFC, is there a way to do that?

Thanks so much for reviewing and devlopment!

**Comment by kevinblighe** [comment]
Hey @northNomad , this is controlled internally via _ggrepel_. However, you can attempt to control which genes are labeled via the `selectLab `parameter. Usually, more labels can also be plot by setting `drawConnetors == TRUE`. One can also simply reduce the size of the labels (`labSize`), which will mean that more can be plot.

Please re-open this issue if this does not fully address the question.

Kind regards,
Kevin
