### ISSUE TITLE
Warning messages: 1: In FUN(X[[i]], ...) : NaNs produced 

### ISSUE THREAD

**Issue by archana433** [kevinblighe/EnhancedVolcano#52]
EnhancedVolcano(res5,
                lab = rownames(res5),
                y = 'log2FoldChange',
                x = 'padj',
                selectLab = c("Zyx","Yes1","Wasf2","Vegfc"),
                title = 'Custom shape & colour over-ride',
                pCutoff = 0.05,
                FCcutoff = 0.5,
                pointSize = keyvals.size,
                labSize = 4.0,
                shapeCustom = keyvals.shape,
                colCustom = keyvals.shape,
                colAlpha = 1,
                legendPosition = 'right',
                legendLabSize = 15,
                legendIconSize = 5.0,
                drawConnectors = TRUE,
                widthConnectors = 0.5,
                colConnectors = 'grey50',
                gridlines.major = FALSE,
                gridlines.minor = FALSE,
                border = 'full',
                borderWidth = 1.0,
                borderColour = 'grey')

when I exchanged the x axis with y axis , I am getting these warning -
Warning messages:
1: In FUN(X[[i]], ...) : NaNs produced
2: Removed 1 rows containing missing values (geom_vline). 
![Screenshot from 2020-07-12 22-01-49](https://user-images.githubusercontent.com/65083903/87251724-77585f80-c48b-11ea-898d-9865799a0dcf.png)

**Comment by kevinblighe** [comment]
Hi, see here: https://www.biostars.org/p/449017/#449022

**Comment by archana433** [comment]
Thank you
