### ISSUE TITLE
Option for rasterization

### ISSUE THREAD

**Issue by benostendorf** [kevinblighe/EnhancedVolcano#53]
Thanks a lot for a great package!

Given the large number of datapoints on a typical volcano plot, these plots often become sluggish to deal with. 
Therefore, it would be fantastic if there was an option to rasterize the output. 

One way I could imagine it would be to have an option to set `raster = TRUE` in the function. This would call `geom_point_rast` from the `ggrastr` [package](https://github.com/VPetukhov/ggrastr) rather than `geom_point`. 

Edit: I submitted a pull request for this. Thanks for considering it!

**Comment by kevinblighe** [comment]
Hi @benostendorf , thanks for the contribution! It will take me some time before I can look through these Pull Requests in great detail.

**Comment by kevinblighe** [comment]
Hey @benostendorf, thanks for these - I have now incorporated them into the main branch and they will propagate to the Bioconductor Devel branch in the coming days. You are also added as Contributor.

If you could do further testing with raster (before the next official Bioc release), that would be great!

Closed in https://github.com/kevinblighe/EnhancedVolcano/pull/55
