### ISSUE TITLE
Both left and right of zero as positive x-axis values

### ISSUE THREAD

**Issue by CodeInTheSkies** [kevinblighe/EnhancedVolcano#58]
Hi Kevin,

Thanks for writing this very useful EnhancedVolcano package!  Lovely!

I have a rather unusual customization scenario, where I have two conditions, say WT and KO, each with their own lists of LogFC and adj_pVals.  I am only interested in the positive LogFCs. But I wish to plot both the conditions in a single plot, where the left of zero would correspond to WT cases (with positive x-axis values), and the right would correspond to the KO cases, again with positive values.  Of course, as per your Vignette, I think I can also choose different colors for the two conditions.

Essentially, since I am not plotting negative logFCs at all, I don't need the negative x-axis part, but instead would like to replace that with the second condition.

I know I can do this another way, where I limit the x-axis to only the positive values, and then plot each condition with a different color, but the problem would be that the points would overlap a lot as they would have similar LogFC values and pValues.  So, it would be best if I can split as left and right for the two conditions, so that I can neatly label the genes too without too much overcrowding.

Do you think this is possible?

Would very much appreciate your insights!

Many thanks.

**Comment by kevinblighe** [comment]
Hey, it's certainly possible to do this but perhaps not with _EnhancedVolcano_ as it's currently designed. You could generate two separate plots and place them side-by-side via _cowplot::plot_grid_ or using the _grid_ and _gridExtra_ packages, or else try to come up with some other cutomised solution.

**Comment by CodeInTheSkies** [comment]
Thanks, Kevin.  Yes, I am aware of these possibilities.  I am looking to see if I can code this somehow, but in case you have some ideas about how to specifically achieve this, i.e., having positive values on the left of zero as well, and also changing the colors for left and right separately, please let me know, if you wouldn't mind.  Thanks.

**Comment by kevinblighe** [comment]
As it turns out, you can sort of 'cheat' to do this via `scale_x_continuous()`. If you take a look at this example from the vignette: https://github.com/kevinblighe/EnhancedVolcano#custom-axis-tick-marks

Now, we can simply change the labels via:
```
p1 +
  ggplot2::coord_cartesian(xlim=c(-6, 6)) +
  ggplot2::scale_x_continuous(
  breaks=seq(-6,6, 1), labels = c(6,5,4,3,2,1,0,1,2,3,4,5,6))
```

<a href="https://ibb.co/Pwdr2r6"><img src="https://i.ibb.co/yWrNzNQ/h.png" alt="h" border="0"></a>

So, that should do it.

**Comment by CodeInTheSkies** [comment]
Thanks a lot, Kevin!  That trick works wonderfully!

**Comment by kevinblighe** [comment]
Excellent!
