### ISSUE TITLE
the id transversion maybe not ftit for all counts matrix

### ISSUE THREAD

**Issue by dj10086** [kevinblighe/EnhancedVolcano#59]
ens <- rownames(airway)

  library(org.Hs.eg.db)
  symbols <- mapIds(org.Hs.eg.db, keys = ens,
    column = c('SYMBOL'), keytype = 'ENSEMBL')
  symbols <- symbols[!is.na(symbols)]
  symbols <- symbols[match(rownames(airway), names(symbols))]
  ens <- rownames(airway)

  library(org.Hs.eg.db)
  symbols <- mapIds(org.Hs.eg.db, keys = ens,
    column = c('SYMBOL'), keytype = 'ENSEMBL')
  symbols <- symbols[!is.na(symbols)]
  symbols <- symbols[match(rownames(airway), names(symbols))]
  rownames(airway) <- symbols
  keep <- !is.na(rownames(airway))
  airway <- airway[keep,]
  keep <- !is.na(rownames(airway))
  airway <- airway[keep,]

use this code in my own data, it report error,  Error in `.rowNamesDF<-`(x, value = value) : mo 'row.names' deplicated permitted
thanks  a lot

**Comment by kevinblighe** [comment]
It seems that you have not actually used any _EnhancedVolcano_ function here (?). The error appears to relate to duplicate rownames in one of your data-frames

**Comment by dj10086** [comment]
I haved used. I tested all the code in this, here is just one error. thanks a lot, I also want you to revise the rna-seq script more robust whenyou are not busy.
![image](https://user-images.githubusercontent.com/61576362/92315502-fa73dd00-f018-11ea-9381-bb2ce921c0d5.png)

**Comment by kevinblighe** [comment]
Hi, to solve this new error, you need to install the version from GitHub. These new changes have not yet been released, officially.

You can try:
`remotes::install_github('kevinblighe/EnhancedVolcano')`

**Comment by dj10086** [comment]
thanks a lot, I willtry now
 I also want you to revise the rna-seq script more robust when you are not busy

**Comment by kevinblighe** [comment]
If you need help with other things, perhaps you can create a question on Biostars?
