### ISSUE TITLE
Control over axis is required.

### ISSUE THREAD

**Issue by lokapal** [kevinblighe/EnhancedVolcano#6]
First of all, thanks for useful script with VERY good documentation and ready-to-use examples! Unfortunately, modules like EnhancedVolcano are rather exception (as for documentation and examples) in R repository and (especially) Bioconductor. 
It seems that it would be good to have more control over axes (ticks marks, frequency of main ticks etc.) I've tried to pass xaxt="n" to EnhancedVolcano and then use standard R axis() function but to no avail.

**Comment by kevinblighe** [comment]
Hey, thank you for the comments! _EnhancedVolcano_ is built using the _ggplot2_ engine, so, it should be possible to 'add on' functionality after you have created the _EnhancedVolcano_ object. For example:

```
p1 <- EnhancedVolcano(...)
p1 + theme(axis.text.x = element_text(face="bold", color="#993333", 
                           size=14, angle=45),
          axis.text.y = element_text(face="bold", color="#993333", 
                           size=14, angle=45))
p1
```
Due to the way that _ggplot2_ inherently behaves, technically, the user can add on any amount of modification after the initial object is created.

There is a a thread on axis manipulation here: http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels

I should probably add examples like this to the vignette for advanced users.

Let me know if this helps.

Kevin

**Comment by kevinblighe** [comment]
Hey, can you confirm that this has helped?

**Comment by lokapal** [comment]
Hello, Kevin! Sorry for the delay!
If I need in full control over, I'd say, X axis it should be something like this one:
If I want to fix X axis from -7, 7 range and draw major ticks every 1 in -6, 6 range and minor ticks every 0.2 in -6, 6 range too than it will be:
EnhancedVolcano(A bunch o all parameters and options etc) + coord_cartesian(xlim=c(-7, 7)) + scale_x_continuous(breaks=seq(-6,6,1), minor_breaks=seq(-6, 6, 0.2))

**Comment by kevinblighe** [comment]
Great! - thank you for the feedback. So, I presume that I can close this thread? I may add this functionality to the main package in the next update.

**Comment by kevinblighe** [comment]
Hey lokapal, I am re-opening this to remind me to implement it in the next main release with Bioc 3.10 (Bioc 3.9 was released just yesterday, May 3). Thanks!

**Comment by lokapal** [comment]
![volc1](https://user-images.githubusercontent.com/6469161/57191061-071a8980-6f2a-11e9-9525-b958d54ba816.png)
Technically, this plot is drawn by the following code:
`EnhancedVolcano(res,lab=res$symbol,x='log2FoldChange',y='padj',
    xlab = bquote(~Log[2]~ 'fold change'),
    ylab = bquote(~-Log[10]~adjusted~italic(P)),
    pCutoff = 0.01,
    FCcutoff = 2,
    transcriptLabSize = 4.0,
    colAlpha = 1,
    legend=c('NS','Log2 FC','Adjusted p-value',
      'Adjusted p-value & Log2 FC'),
    legendPosition = 'bottom',
    legendLabSize = 10,
    legendIconSize = 3.0
) + coord_cartesian(xlim=c(-14,27),ylim=c(0,20)) + 
   scale_x_continuous(breaks=seq(-15,30,5), minor_breaks=seq(-14,27,1)) + 
   scale_y_continuous(minor_breaks=seq(1,20,1))
`

**Comment by kevinblighe** [comment]
Continued here:
https://github.com/kevinblighe/EnhancedVolcano/issues/17
