### ISSUE TITLE
Volcano plot it's produced but wihout any labels

### ISSUE THREAD

**Issue by matrs** [kevinblighe/EnhancedVolcano#63]
Hello, 
thanks for this package, seems to be very useful. I tried the demo code from the vignette and It worked as expected. The problem that I'm having is with a small dataset (I'm attaching it). I can produce a volcano plot but I don't why the labels aren't displayed in the plot. I tried multiple  other arguments, but I really don't understand  why the labels aren't part of the plot, it should be very straightforward to do it: 

```r
volc_plot <- EnhancedVolcano(protlist_qvals, lab = "labels", x = "FC in CoCl2", 
                             y ="N: Student's T-test q-value CoCl2_CTR", 
                             xlim = c(-0.4,5),
                             title = "CoCl2")
``` 
![volc_cocl2](https://user-images.githubusercontent.com/12502882/97087584-92497c80-1601-11eb-8bc7-08a7356e1d0f.png)

Here is small tab separated file to reproduce it (I changed the extension because github doesn't allow csv/tsv extensions).

[enhancedVol_list.xlsx](https://github.com/kevinblighe/EnhancedVolcano/files/5433317/enhancedVol_list.xlsx)

**Comment by kevinblighe** [comment]
Please double-check the vignette. Your `lab` argument is incorrect
