### ISSUE TITLE
Getting an error when installing EnhancedVolano pkg

### ISSUE THREAD

**Issue by venuraherath** [kevinblighe/EnhancedVolcano#64]
Hi Kevin,

When I try to install EnchancedVolcano, I get the following error at the end (all other dependencies install without any issue)
```
Error: Failed to install 'EnhancedVolcano' from GitHub:
  ERROR: failed to lock directory ‘C:\Users\venura\Documents\R\win-library\4.0’ for modifying
Try removing ‘C:\Users\venura\Documents\R\win-library\4.0/00LOCK’
```
Can you help me with this issue?
I am using RStudio ver 1.3.1093 and R-4.0.3
Thanks.

**Comment by kevinblighe** [comment]
Hey, this means that some prior installation failed. You just need to delete the following directory, and it should work:

```
C:\Users\venura\Documents\R\win-library\4.0/00LOCK
```
Kevin
