### ISSUE TITLE
Citation for EnhancedVolcano?

### ISSUE THREAD

**Issue by ayushnoori** [kevinblighe/EnhancedVolcano#65]
Hi @kevinblighe - I'd like to cite EnhancedVolcano in a forthcoming publication. Is there a formal paper on the package which I can cite, or should I simply cite the repository? Thanks.

**Comment by kevinblighe** [comment]
Hey @ayushnoori, thank you for using this package.

Did you try typing `citation('EnhancedVolcano')` at the command prompt in R?

```
Kevin Blighe, Sharmila Rana and Myles Lewis (2020). EnhancedVolcano: Publication-ready volcano plots with enhanced colouring and labeling. R package version 1.7.14. https://github.com/kevinblighe/EnhancedVolcano
```
There is no publication for this package, but it is being cited by many others - see here: https://scholar.google.com/scholar?oi=bibs&hl=en-GB&cites=12021273313259886118&as_sdt=5

**Comment by ayushnoori** [comment]
Thanks @kevinblighe, surmised as much but thought I'd check.
