### ISSUE TITLE
Weird enhanced volcano plot after performing LFCshrinage 

### ISSUE THREAD

**Issue by cannico30** [kevinblighe/EnhancedVolcano#68]
Hi everyone, 
I used the TCGA database for melanoma to perform DEseq2 analysis. After I performed the lfcshrinkage command, my enhanced volcano plot looks very weird. 

Does anybody have an idea? 

Thank you very much in advance. 
the first plot is performed without lfc shrinkage and the second one with. 
![volcano plot without lfc](https://user-images.githubusercontent.com/76188205/102557869-65f22f80-4089-11eb-8988-c80751409436.png)

![volcano plot after lfcs](https://user-images.githubusercontent.com/76188205/102557796-3b07db80-4089-11eb-8d61-24116e7452f9.png)

**Comment by kevinblighe** [comment]
Hi, I think that this is more of an issue with the lfc shrinkage method of _DESeq2_. Sorry.

**Comment by cannico30** [comment]
Hi Kevin, 

thank you very much for your answer. I do have another question: What is the default setting for the volcano plots to assume the fold change is 0? Because when I look in my data output the fold change is never 0, it is just very small. 

Best wishes, 

Nico
