### ISSUE TITLE
Y - axis control to manage height of plot

### ISSUE THREAD

**Issue by sid5427** [kevinblighe/EnhancedVolcano#74]
Hi Kevin,

Thanks for this awesome package!

Is there a simple way to manage the height of a generated plot?

Say for the example plot below - I want to only see the plot upto Y-axis = 5.0 level. Essentially streamline the plot?

![prot_plot](https://user-images.githubusercontent.com/7871253/114164365-d51db900-98f0-11eb-9786-0644a0fa3c3e.jpeg)

Thanks,
Sid

**Comment by kevinblighe** [comment]
Hi Sid, the extra white-space in your plot is related to how I set the default value of ylim, which is:
`ylim = c(0, max(-log10(toptable[[y]]), na.rm=TRUE) + 5)`

I think that you can just change this to:

`ylim = c(0, max(-log10(toptable[[y]]), na.rm=TRUE) + 1)`

... or just
`ylim = c(0, 5)`

That should work!

Kevin

**Comment by roberthardt** [comment]
Well apparently my installation of R does not now the toptable function, so whenever I want to adjust the axes extra white-space it give some an error:

"Error in EnhancedVolcano(data, lab = data$PG.Genes, selectLab = custom_label$PG.Genes,  : 
  object 'toptable' not found"

Best

Robert
