### ISSUE TITLE
Color and label only genes of interest

### ISSUE THREAD

**Issue by aditisk** [kevinblighe/EnhancedVolcano#76]
Hi @kevinblighe,

I have a question about how to color and label only some genes that I am interested in on the Volcano plot. These are not the top 100 genes hence a p-value or logFC cut-off won't work. Ideally I want 3 colors: non significant genes, significant but not in my list and genes in my list.

Any thoughts on if this is possible ? Thanks a lot for your help.

**Comment by kevinblighe** [comment]
Hi, you should be able to do this by following the example here:
https://github.com/kevinblighe/EnhancedVolcano#over-ride-colour-andor-shape-scheme-with-custom-key-value-pairs

You may also need to make use of the `selectLab` parameter.

Can you try that? - thanks!

Kevin

**Comment by aditisk** [comment]
Hi @kevinblighe, thanks for the suggestion. I was able to get this to work.
