### ISSUE TITLE
any possibility of converting existing enhancedvolcano to an interactive one?

### ISSUE THREAD

**Issue by klai001** [kevinblighe/EnhancedVolcano#77]
Hi Kevin
wondering if there's any possibility of converting existing enhancedvolcano to an interactive one using an argument in the EnhancedVolcano package?
something similar to plotly maybe.

**Comment by kevinblighe** [comment]
There was a question on Biostars related to this, and, although it worked, I was not too pleased with the functionality. Please see: https://www.biostars.org/p/421750/#421769

Other than that, I have no immediate intention to develop the package further such that it would then implicitly support this, mostly due to time constraints.

Kevin

**Comment by kevinblighe** [comment]
Please re-open issue if needed

**Comment by mauritsunkel** [comment]
Hi! As inspired by your Biostars thread, I managed a minimal example using Shiny + EnhancedVolcano + plotly for others interested: 

Crosslinking with #114 

```
library(shiny)
library(EnhancedVolcano)
library(plotly)

ui <- fluidPage(
  plotlyOutput("volcano_plot"),
  verbatimTextOutput("selected_genes")
)

server <- function(input, output, session) {
  output$volcano_plot <- renderPlotly({
    df <- data.frame(
      logFC = rnorm(1000),
      pval = runif(1000),
      gene = paste0("Gene", 1:1000)
    )
    p <- EnhancedVolcano(
      df,
      lab = df$gene,
      x = "logFC",
      y = "pval"
    )

    p2 <- ggplotly(p + aes(key = gene, x = logFC, y = -log10(pval)))

  })

  output$selected_genes <- renderPrint({
    selected <- event_data("plotly_selected")
    print(selected)
    if (is.null(selected)) return("No selection")
    unique(selected$key)
  })
}

shinyApp(ui, server)
```
