### ISSUE TITLE
Feature request: option to have thresholds values drawn.

### ISSUE THREAD

**Issue by lokapal** [kevinblighe/EnhancedVolcano#8]
It would be good to have option/parameter to mark threshold(s) values explicitly at axes. At least, at ordinate (Y) axis. Surely I can do it lately in Inkscape/Illustrator/CorelDraw/Acrobat. But it would be convenient to have it "automatically" drawn in the Enhanced Volcano.
Thanks in advance!

**Comment by kevinblighe** [comment]
Hey lokapal, when you say 'mark', what do you have in mind, specifically? Do you mean, for example, large tick marks at certain values? Currently, one can add multiple horizontal lines across the plot at different threshold values, but this may not be what you want.

**Comment by kevinblighe** [comment]
Closing as it has been 2 weeks since original reply. I will take your suggestions on board. Thanks!

**Comment by lokapal** [comment]
![volc1](https://user-images.githubusercontent.com/6469161/57190780-0502fb80-6f27-11e9-8b5d-551e97a61eed.png)
I mean it would be useful to see values marked by red question marks. The most useful (for biologists) it would be to see at ordinate axis something like padj=0.01 (or padj=1.0 x 10-2) instead of simple "2"
