### ISSUE TITLE
Raster option not recognized

### ISSUE THREAD

**Issue by cschmidl** [kevinblighe/EnhancedVolcano#81]
Hello, when I install with BiocManager::install('EnhancedVolcano') I only get Versino 1.4 (not 1.11), and can not use the raster = TRUE function as it is not recognized. I installed the dev version already as I thought this might help, but I can not get it to run. Thanks for your help!

**Comment by kevinblighe** [comment]
Hi, which version of R are you using?
That is strange... the Bioconductor landing page says v1.10: https://bioconductor.org/packages/release/bioc/html/EnhancedVolcano.html
The version should be v1.9

**Comment by kevinblighe** [comment]
Please re-open if needed.
