### ISSUE TITLE
duplicate rownames error

### ISSUE THREAD

**Issue by Anto007** [kevinblighe/EnhancedVolcano#83]
I'm new to R and I'm trying to run R package EnhancedVolcano for generating a plot. My input csv file is a list of differentially expressed genes from DESeq2. The first column contains gene names that do not occur uniquely and so it continues to give `duplicate rownames error`. I hope there's a way to avoid this? My input csv file is available on [Dropbox](https://www.dropbox.com/s/ioy73maam27r92d/Volcano_DEGlist_Age12_vs_Age0.csv?dl=0)

The code I tried is the below.

```
library(EnhancedVolcano)
results <- read.csv("Volcano_DEGlist_Age12_vs_Age0.csv", row.names=1, header=T)
toptable <- as.data.frame(results)
EnhancedVolcano(toptable, lab=rownames(toptable),x="log2FoldChange",y="padj")
```

Any help here would be highly appreciated!

**Comment by kevinblighe** [comment]
Hi @Anto007 , I find this error strange. If you run the `as.data.frame()` function, and assuming that there are duplicate rownames, the error should be thrown at that step, not after you run `EnhancedVolcano()`. Can you confirm?

**Comment by Anto007** [comment]
Apologies for not making this clear; the error indeed came up at the read.csv step. I got around the issue by going for `read_csv `function instead from `tidyverse` also by introducing a new header 'name' to column 1. I then used the following code to make EnhanceVolcano work:

`EnhancedVolcano(df, lab=df$name, x="log2FoldChange", y="padj")`
