### ISSUE TITLE
Not able to install EnhancedVolcano? Not able to install proj4

### ISSUE THREAD

**Issue by mathavan10** [kevinblighe/EnhancedVolcano#88]
Hi Kevin,
I am trying to install EnhancedVolcano R package but I could not able to do it. The error message showed as it is dependency errors - proj package. I am not able to install proj4

Please guide me 

The error message is pasted below

** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -DUSE_PROJ6_API=1     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c p4.c -o p4.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o proj4.so p4.o -lproj -lsqlite3 -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -lproj
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: proj4.so] Error 1
ERROR: compilation failed for package ‘proj4’
* removing ‘/home/nucleome/R/x86_64-pc-linux-gnu-library/4.1/proj4’
Warning in install.packages :
  installation of package ‘proj4’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpj4p6ye/downloaded_packages’

**Comment by rajkump** [comment]
Having the same issue
Warning message:
In .inet_warning(msg) :
  package ‘proj4 ’ is not available for Bioconductor version '3.13'

**Comment by kevinblighe** [comment]
Thank you for posting that solution on Bioconductor Support forum
