### ISSUE TITLE
Volcano plot without any labels 

### ISSUE THREAD

**Issue by DM087** [kevinblighe/EnhancedVolcano#90]
Hi Kevin,
thanks for the wonderful package! 
I am trying to use it on Mac iOS and it seems that the `lab` is not working for me. The code that I am trying to run is

`EnhancedVolcano(data,lab = data$Gene,x = 'beta',y = 'P')`

`str(data)`

`'data.frame':	7 obs. of  3 variables:
 $ Gene: chr  "Name1" "Name2" "Name3" "Name4" ...
 $ beta: num  0.0118 0.014 0.012 0.0134 0.0117 ...
 $ P   : num  7.10e-78 2.17e-69 6.50e-63 1.72e-62 1.38e-61 ...`

Any thoughts on what might be going wrong here?
Thanks

**Comment by mathavanpu** [comment]
EnhancedVolcano(p, lab = rownames(p), x = "log2FoldChange", y = "padj", title = 'PCGS2_Vs_PCGS4', selectLab = c(""), pCutoff = 10e-2, FCcutoff = 1 , pointSize = 3.0, labSize = 3.0 , ylim = c(0,50), xlim = c(-6,6))

**Comment by kevinblighe** [comment]
Hi, can you define '_not working_'?

**Comment by kevinblighe** [comment]
Please re-open if the issue persists.
