### ISSUE TITLE
Generate plot without any title - change of title/legend font size

### ISSUE THREAD

**Issue by JuHey** [kevinblighe/EnhancedVolcano#91]
Great tool!

Is there a way to turn off plotting of default title/subtitle? How would I change font size for title/legends?

With best wishes

**Comment by kevinblighe** [comment]
Hi, you just need to set these values (of `title`, `subtitle`, and `caption`) to `NULL`.

Kind regards,
Kevin

**Comment by JuHey** [comment]
Thank you, Kevin!

Wishing you a Happy New Year!
