### ISSUE TITLE
Enhanced Volcano plot not loading in my library

### ISSUE THREAD

**Issue by EmCutlerUCL** [kevinblighe/EnhancedVolcano#92]
Hi there, 

This package was working fine a few days ago but now when I type 
library(EnhancedVolcano) into R studio, it doesn't load and I get the following error message (screenshot attached).

<img width="715" alt="Screenshot 2021-12-10 at 14 46 47" src="https://user-images.githubusercontent.com/79911814/145592514-888229e1-b89b-4a76-9391-f0d20657eb08.png">

Please can I have some help with this?

Thanks,
Emily :)

**Comment by kevinblighe** [comment]
Hi Emily, that's strange. Can you first try to install _ggrastr_ via:
`install.packages('ggrastr')`
?

**Comment by kevinblighe** [comment]
Apologies for delay in responding, but I will assume that this will solve the problem. If not, please re-open the issue.
Thanks and kind regards,
Kevin
