### ISSUE TITLE
Labels not working 

### ISSUE THREAD

**Issue by margotcj** [kevinblighe/EnhancedVolcano#93]
hi! When I use the  "selectLab = c", and choose various genes, (I chose 10 in this instance ), not all of them show up on my plot. I checked to make sure that they were within the range of the p value and log fold change. Do you know why this could be? When I add the "drawconnectors = TRUE" it solves part of the issue, but it still does not show all of the genes. Also, It makes the plot look a bit messier when I add this option. 

Thank you for your help!

**Comment by kevinblighe** [comment]
Hi, please show the code that you are running. Please also show the top portion of your input results table.

If the plot seems 'messier' with `drawconnectors = TRUE`, then try to alter the p-value threshold (`pcutoff`)

**Comment by kevinblighe** [comment]
Please re-open if the issue persists.

**Comment by jcshuy** [comment]
Hi there! Thanks for the awesome package. I apologize if you have stated the solution elsewhere and I have missed it, but I've had the same issue as two of my labels are right next to each other. I read through some other Github issues and your workarounds on support.bioconductor but unfortunately I haven't seemed to find a proper fix yet.

Currently I've bypassed it by just having no arrowheads and setting the size super tiny using the following code:
```
EnhancedVolcano(gene_id, 
                lab = gene_id$gene_id, 
                selectLab = c("APP", "TLR2", "APOE", "C3", "HIF1A-AS2", "HIF1A", "LRRK2", "MRC1"), 
                x = "logFC", 
                y = "Pval",
                labSize = 5.0, 
                subtitle = NULL, 
                pCutoff = 5e-2, 
                FCcutoff = 0, 
                axisLabSize = 30, 
                gridlines.minor = FALSE, 
                gridlines.major = FALSE,
                labFace = "italic", 
                legendLabSize = 0, 
                legendIconSize = 0, 
                pointSize = 2,
                drawConnectors = TRUE,
                widthConnectors = 0,
                arrowheads = F,
                colCustom = keyvals) 
```

Which results in the following:

<img width="1099" alt="Image" src="https://github.com/user-attachments/assets/54924896-ea53-4204-976c-80a455773fa5" />

But I was wondering if there was a way to turn off the repel setting altogether? I see in the docs that max.overlaps is set to "Inf" when drawConnectors is on, but running the same code as above with `max.overlaps = Inf` while `drawConnectors = F` yields the same result with the last DEG being cut off.

Thank you again!
