### ISSUE TITLE
How to point the overlapping genes in enhanced volcano plot?

### ISSUE THREAD

**Issue by mathavanpu** [kevinblighe/EnhancedVolcano#94]
Hello Kevin,
I want to create an enhanced volcano plot of top-up/down-regulated genes.  While executing the script some genes are not shown in the plot(only 15 genes are shown). I referred link that is related my query in the Biostar but I could not able to solve it. 

could please help me
https://www.biostars.org/p/457119/

**Comment by kevinblighe** [comment]
Hi, it is expected behaviour that not all genes will show. This permits that the plot space is not 'cluttered'. You can try to add more labels by increasing the value of `max.overlaps`, but only when `drawConnectors `is `TRUE`.
