### ISSUE TITLE
citationURL: Remove typo from citation link

### ISSUE THREAD

**Issue by KasperThystrup** [kevinblighe/EnhancedVolcano#96]
Hi.

Thanks for the nice tool!

Easy issue to fix here: In your readme (and documentation) you ask to include a citation with a github link. This link has accidentally adopted the "." at the end of the line, this results in a 404 on github.

Cheers 
 K

**Comment by kevinblighe** [comment]
Thanks @KasperThystrup - I will implement this when I am next updating the packages.

**Comment by hp961203** [comment]
Hi.
Thanks for the very awesome tool!
But my software reports an error, and I don't know what the error is
'Error in .subset2(x, i, exact = exact) : 
  recursive indexing failed at level 2'
I hope you have time to help see
Cheers
hp

**Comment by kevinblighe** [comment]
Hi @hp961203 , that is unrelated to the topic of this particular Github issue. Please create a new issue.
